module.exports = {
  testEnvironment: "jsdom",
  moduleDirectories: ["node_modules", "src"],
  modulePaths: [
    "<rootDir>/src",
    "<rootDir>/../..",
    "<rootDir>/../../node_modules",
  ],
  moduleNameMapper: {
    "^@docspace/client/src/(.*)$": "<rootDir>/src/$1",
    "^@docspace/shared/constants$": "<rootDir>/../shared/constants",
    "^@docspace/shared/store$": "<rootDir>/__mocks__/authStore.js",
    "^@docspace/shared/utils/i18next-http-backend$": "<rootDir>/__mocks__/i18next-http-backend.js",
    "^@docspace/shared/utils$": "<rootDir>/__mocks__/sharedUtils.js",
    "^@docspace/shared/utils/(.*)$": "<rootDir>/__mocks__/sharedUtils.js",
    "^@docspace/shared/enums$": "<rootDir>/__mocks__/enums.js",
    "^@docspace/shared/api/files/filter$": "<rootDir>/__mocks__/filesFilter.js",
    "^@docspace/shared/api/rooms/filter$": "<rootDir>/__mocks__/roomsFilter.js",
    "^ASSETS_DIR/locales/(.*)\\?url$": "<rootDir>/__mocks__/translationUrlMock.js",
    "^ASSETS_DIR/locales/(.*)\\.(json|js)$": "<rootDir>/__mocks__/translationMock.js",
    "^PUBLIC_DIR/locales/(.*)\\?url$": "<rootDir>/__mocks__/translationUrlMock.js",
    "^PUBLIC_DIR/locales/(.*)\\.(json|js)$": "<rootDir>/__mocks__/translationMock.js",
    "^@docspace/shared/components/toast$": "<rootDir>/__mocks__/toastr.js",
    "^@docspace/shared/components/icon-button/IconButton.styled$": "<rootDir>/__mocks__/iconButtonComponents.js",
    "^@docspace/shared/components/icon-button/IconButton$": "<rootDir>/__mocks__/iconButtonComponents.js",
    "^@docspace/shared/components/toast/Toast.styled$": "<rootDir>/__mocks__/toastStyled.js",
    "^@docspace/shared/components/toast/Toast$": "<rootDir>/__mocks__/toastComponents.js",
    "^@docspace/shared/components/text/Text.styled$": "<rootDir>/__mocks__/textComponents.js",
    "^@docspace/shared/components/text/Text$": "<rootDir>/__mocks__/textComponents.js",
    "^@docspace/shared/components/box/Box.styled$": "<rootDir>/__mocks__/boxComponents.js",
    "^@docspace/shared/components/box/Box$": "<rootDir>/__mocks__/boxComponents.js",
    "^@docspace/shared/components/toast/svg$": "<rootDir>/__mocks__/toastSvg.js",
    "^@docspace/shared/utils/socket$": "<rootDir>/__mocks__/socket.js",
    "^@docspace/shared/utils/getViewForCurrentRoom$": "<rootDir>/__mocks__/sharedUtils.js",
    "^@docspace/shared/utils/combineUrl$": "<rootDir>/__mocks__/sharedUtils.js",
    "^@docspace/shared/utils/common$": "<rootDir>/__mocks__/commonUtils.js",
    "^@docspace/shared/api$": "<rootDir>/__mocks__/api.js",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/svgMock.js",
    "^PUBLIC_DIR/images/(.*)\\.(svg)$": "<rootDir>/__mocks__/svgMock.js",
    "^ASSETS_DIR/images/(.*)\\.(svg)$": "<rootDir>/__mocks__/svgMock.js",
    "^@docspace/shared/api/people/filter$": "<rootDir>/__mocks__/filter.js",
    "^@docspace/shared/api/groups/filter$": "<rootDir>/__mocks__/groupsFilter.js",
    "^@docspace/shared/api/people$": "<rootDir>/__mocks__/people.js",
    "^@docspace/common/(.*)$": "<rootDir>/../../common/$1",
    "^@docspace/components/(.*)$": "<rootDir>/../../components/$1",
    "^@docspace/shared/(.*)$": "<rootDir>/../shared/src/$1",
    "^@docspace/store/(.*)$": "<rootDir>/src/store/$1",
    "^@docspace/(.*)$": "<rootDir>/../$1/src",
    "^SRC_DIR/(.*)$": "<rootDir>/src/$1",
    "^PUBLIC_DIR/images/logo/(.*)\\.svg\\?url$": "<rootDir>/__mocks__/svgMock.js",
    "^PUBLIC_DIR/images/(.*)\\.svg\\?url$": "<rootDir>/__mocks__/svgMock.js",
    "^PUBLIC_DIR/images/logo/(.*)\\.(svg|ico)$": "<rootDir>/__mocks__/fileMock.js",
    "^PUBLIC_DIR/(.*)$": "<rootDir>/public/$1",
    "^PACKAGE_FILE$": "<rootDir>/package.json",
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    "\\.(mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
  },
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.js"],
  testPathIgnorePatterns: ["/node_modules/", "/dist/"],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": [
      "babel-jest",
      { configFile: "./babel.config.js" },
    ],
  },
  transformIgnorePatterns: ["/node_modules/(?!(hex-rgb|other-esm-packages)/)"],
  collectCoverageFrom: [
    "src/**/*.{js,jsx}",
    "!src/**/*.test.{js,jsx}",
    "!src/setupTests.js",
    "!src/index.js",
  ],
  coverageThreshold: {
    global: {
      statements: 50,
      branches: 50,
      functions: 50,
      lines: 50,
    },
  },
  roots: ["<rootDir>/src"],
};
