import getMockResponse, {
  settingsSuccessNoAuth,
  settingsSuccessWithAuth,
  settingsError,
  settingsForbidden,
  settingsNotFound,
  settingsSuccessWithAuthWizard,
  settingsPasswordSuccess,
  machineNameSuccess,
  isLicenseRequiredFalseSuccess,
  isLicenseRequiredTrueSuccess,
  portalTimeZonesSuccess,
  portalCulturesSuccess,
  colorThemeSuccess,
} from "./settings";

export {
  getMockResponse,
  settingsSuccessNoAuth,
  settingsSuccessWithAuth,
  settingsError,
  settingsForbidden,
  settingsNotFound,
  settingsSuccessWithAuthWizard,
  settingsPasswordSuccess,
  machineNameSuccess,
  isLicenseRequiredFalseSuccess,
  isLicenseRequiredTrueSuccess,
  portalTimeZonesSuccess,
  portalCulturesSuccess,
  colorThemeSuccess,
};
