export const ThemeType = {
  IconButton: "iconButton",
  IconButtonPin: "iconButtonPin",
  IndicatorFilterButton: "indicatorFilterButton",
  FilterBlockItemTag: "filterBlockItemTag",
  IconWrapper: "iconWrapper",
  VersionBadge: "versionBadge",
  InputBlock: "inputBlock",
  LinkForgotPassword: "linkForgotPassword",
  LoadingButton: "loadingButton",
  InfoPanelToggle: "infoPanelToggle",
  Link: "link",
  IndicatorLoader: "indicatorLoader",
  Progress: "progress",
  IconButtonMute: "iconButtonMute",
};
