packages:
  - packages/*
catalog:
  "@babel/cli": 7.25.7
  "@babel/core": 7.25.8
  "@babel/eslint-parser": 7.25.8
  "@babel/plugin-proposal-class-properties": 7.18.6
  "@babel/plugin-proposal-export-default-from": 7.25.8
  "@babel/plugin-proposal-export-namespace-from": 7.18.9
  "@babel/plugin-proposal-private-property-in-object": 7.21.11
  "@babel/plugin-transform-runtime": 7.25.7
  "@babel/preset-env": 7.25.8
  "@babel/preset-react": 7.25.7
  "@babel/preset-typescript": 7.25.7
  "@babel/runtime": 7.25.7
  "@codemirror/lang-javascript": 6.2.2
  "@emotion/babel-preset-css-prop": 10.2.1
  "@floating-ui/dom": 1.6.13
  "@emotion/styled": 10.3.0
  "@hcaptcha/react-hcaptcha": 1.11.0
  "@onlyoffice/docspace-sdk-js": 1.1.0
  "@onlyoffice/document-editor-react": 1.5.1
  "@playwright/test": 1.48.0
  "@react-spring/web": 9.7.5
  "@serdnam/pino-cloudwatch-transport": 1.0.4
  "@storybook/addon-actions": 7.6.20
  "@storybook/addon-contexts": 5.3.21
  "@storybook/addon-controls": 7.6.20
  "@storybook/addon-designs": 8.0.3
  "@storybook/addon-docs": 7.6.20
  "@storybook/addon-essentials": 7.6.20
  "@storybook/addon-links": 7.6.20
  "@storybook/addon-viewport": 7.6.20
  "@storybook/addons": 7.6.20
  "@storybook/components": 7.6.20
  "@storybook/manager-api": 7.6.20
  "@storybook/react-webpack5": 7.6.20
  "@storybook/react": 7.6.20
  "@svgr/webpack": 5.5.0
  "@testing-library/dom": 9.3.4
  "@testing-library/jest-dom": 6.6.3
  "@testing-library/react": 14.3.1
  "@testing-library/user-event": 14.5.2
  "@types/accept-language-parser": 1.5.6
  "@types/compression": 1.7.5
  "@types/cookie-parser": 1.4.7
  "@types/crypto-js": 4.2.2
  "@types/element-resize-detector": 1.1.6
  "@types/eslint": 8.56.12
  "@types/express": 4.17.21
  "@types/file-saver": 2.0.7
  "@types/he": 1.2.3
  "@types/i18next-fs-backend": 1.1.5
  "@types/identity-obj-proxy": 3.0.2
  "@types/jest": 29.5.13
  "@types/lodash": 4.17.10
  "@types/luxon": 3.4.2
  "@types/morgan": 1.9.9
  "@types/nconf": 0.10.7
  "@types/node": 20.17.14
  "@types/react-avatar-editor": 13.0.3
  "@types/react-dom": 18.3.1
  "@types/react-google-recaptcha": 2.1.9
  "@types/react-text-mask": 5.4.14
  "@types/react-transition-group": 4.4.11
  "@types/react-virtualized": 9.21.30
  "@types/react-window-infinite-loader": 1.0.9
  "@types/react-window": 1.8.8
  "@types/react": 18.3.11
  "@types/sjcl": 1.0.34
  "@types/styled-components": 5.1.34
  "@types/utif": 3.0.5
  "@types/winston": 2.4.4
  "@typescript-eslint/eslint-plugin": 7.1.0
  "@typescript-eslint/parser": 7.1.0
  "@uiw/codemirror-theme-github": 4.23.5
  "@uiw/react-codemirror": 4.23.5
  "@use-gesture/react": 10.3.1
  "@wojtekmaj/enzyme-adapter-react-17": 0.8.0
  attr-accept: 2.2.4
  axios: 0.22.0
  babel-eslint: 10.1.0
  babel-jest: 29.7.0
  babel-loader: 8.4.1
  babel-plugin-inline-react-svg: 1.1.2
  babel-plugin-styled-components: 2.1.4
  babel-plugin-transform-dynamic-import: 2.1.0
  babel-plugin-transform-react-remove-prop-types: 0.4.24
  babel-plugin-transform-rename-import: 2.3.0
  babel-preset-react-app: 9.1.2
  classnames: 2.5.1
  clean-webpack-plugin: 4.0.0
  cnbuilder: 3.1.0
  copy-to-clipboard: 3.3.3
  copy-webpack-plugin: 9.1.0
  cross-env: 6.0.3
  cross-fetch: 3.1.8
  crypto-js: 4.2.0
  css-loader: 6.11.0
  csvjson-json_beautifier: 5.0.4
  element-resize-detector: 1.2.4
  email-addresses: 3.1.0
  enzyme: 3.11.0
  eslint-config-airbnb-typescript: 17.1.0
  eslint-config-airbnb: 19.0.4
  eslint-config-next: 14.2.15
  eslint-config-prettier: 9.1.0
  eslint-import-resolver-webpack: 0.13.9
  eslint-interactive: 11.1.0
  eslint-plugin-import: 2.31.0
  eslint-plugin-jsx-a11y: 6.10.0
  eslint-plugin-prettier: 5.2.1
  eslint-plugin-react-hooks: 5.1.0
  eslint-plugin-react: 7.37.1
  eslint-plugin-storybook: 0.9.0
  eslint-webpack-plugin: 4.2.0
  eslint: 8.57.1
  external-remotes-plugin: 1.0.0
  fast-deep-equal: 3.1.3
  file-loader: 6.2.0
  file-saver: 2.0.5
  firebase: 10.14.1
  framer-motion: 4.1.17
  global: 4.4.0
  he: 1.2.0
  heic2any: 0.0.4
  hex-rgb: 5.0.0
  html-loader: 4.2.0
  html-to-react: 1.7.0
  html-webpack-plugin: 5.6.0
  i18next-http-backend: 2.6.2
  i18next: 23.7.19
  identity-obj-proxy: 3.0.0
  jest-environment-jsdom: 29.7.0
  jest-styled-components: 7.2.0
  jest: 29.7.0
  json-loader: 0.5.7
  local-web-server: 5.4.0
  lodash: 4.17.21
  lodash.debounce: 4.0.8
  luxon: 3.5.0
  madge: 6.1.0
  mini-css-extract-plugin: 2.9.2
  mobx-react: 7.6.0
  mobx: 6.13.5
  mocha-junit-reporter: 2.2.1
  mocha-multi: 1.1.7
  mocha: 9.2.2
  mochawesome: 7.1.3
  moment-timezone: 0.5.46
  moment: 2.30.1
  nconf: 0.12.1
  next: 14.2.23
  nodemon: 2.0.22
  npm-run-all: 4.1.5
  nx: 20.3.1
  pino-pretty: 11.3.0
  pino-roll: 2.2.0
  pino: 9.5.0
  postcss: 7.0.39
  prettier: 3.3.3
  prop-types: 15.8.1
  query-string: 7.1.3
  queue-promise: 2.2.1
  rc-tree: 5.10.0
  re-resizable: 6.10.0
  react-autosize-textarea: 7.1.0
  react-avatar-editor: 13.0.2
  react-colorful: 5.6.1
  react-content-loader: 7.0.2
  react-countdown: 2.3.6
  react-device-detect: 2.2.3
  react-docgen-typescript-plugin: 1.0.8
  react-dom: 18.3.1
  react-draggable: 4.4.6
  react-dropzone: 11.7.1
  react-google-recaptcha: 3.1.0
  react-hammerjs: 1.0.1
  react-hcaptcha: 0.1.1
  react-hotkeys-hook: 3.4.7
  react-i18next: 14.0.1
  react-json-pretty: 2.2.0
  react-lifecycles-compat: 3.0.4
  react-markdown: 9.0.1
  react-onclickoutside: 6.13.1
  react-player: 1.15.3
  react-router-dom: 6.27.0
  react-router: 5.2.0
  react-scrollbars-custom: 4.1.1
  react-smartbanner: 5.1.4
  react-string-format: 0.1.4
  react-svg: 16.1.34
  react-text-mask: 5.5.0
  react-toastify: 10.0.6
  react-tooltip: 5.28.0
  react-transition-group: 4.4.5
  react-values: 0.3.3
  react-viewer: 3.2.2
  react-virtualized-auto-sizer: 1.0.24
  react-virtualized: 9.22.5
  react-window-infinite-loader: 1.0.9
  react-window: 1.8.10
  react: 18.3.1
  remark-gfm: 4.0.0
  resize-image: 0.1.0
  sass: 1.79.5
  sass-loader: 16.0.4
  screenfull: 5.2.0
  serve: 14.2.3
  shx: 0.3.4
  sjcl: 1.0.8
  socket.io-client: 4.8.0
  source-map-loader: 3.0.2
  storybook-dark-mode: 3.0.3
  storybook: 7.6.20
  styled-components: 5.3.11
  style-loader: 3.3.4
  svg-inline-loader: 0.8.2
  terser-webpack-plugin: 5.3.10
  terser: 5.34.1
  ts-migrate: 0.1.35
  ts-node: 10.9.2
  ts-pattern: 5.5.0
  ts-jest: 29.2.5
  typescript: 5.6.3
  use-resize-observer: 9.1.0
  utif: 3.1.0
  webpack-bundle-analyzer: 4.10.2
  webpack-cli: 4.10.0
  webpack-dev-server: 4.15.2
  webpack-filter-warnings-plugin: 1.2.1
  webpack-manifest-plugin: 5.0.0
  webpack-merge: 5.10.0
  webpack: 5.95.0
  windows-iana: 5.1.0
  workbox-window: 6.6.0
  zoom-level: 2.5.0
