export const mockData = [
  {
    id: 1,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "(Existing account)",
    type: "Docspace admin",
  },
  {
    id: 2,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 3,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 4,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 5,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 6,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 7,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 8,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 9,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 10,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 11,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 12,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
];
