export const mockData = [
  {
    id: 1,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "(Existing account)",
    type: "Docspace admin",
  },
  {
    id: 2,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 3,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 4,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 5,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 6,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 7,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 8,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 9,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 10,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 11,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 13,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 14,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 15,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 16,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 17,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 18,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 19,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 20,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 21,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 22,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 23,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 24,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 25,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 26,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 27,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 28,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 29,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 30,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 31,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 32,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 33,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 34,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 35,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 36,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
];
