export const mockData = [
  {
    id: 1,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "(Existing account)",
    type: "Docspace admin",
  },
  {
    id: 2,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 3,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 4,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 5,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 6,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 7,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 8,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 9,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 10,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 11,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 13,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 14,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 15,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 16,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 17,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 18,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 19,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 20,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 21,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 22,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 23,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 24,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 25,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 26,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 27,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 28,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 29,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 30,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 31,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 32,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 33,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 34,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 35,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 36,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 37,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 38,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 39,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 40,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 41,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 42,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 43,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 44,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 45,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 46,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 47,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 48,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 49,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 50,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 51,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 52,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 53,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 54,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 55,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 56,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 57,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 58,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 59,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 60,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 61,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 62,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 63,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 64,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 65,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 66,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 67,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 68,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 69,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 70,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 71,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 72,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 73,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 74,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 75,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 76,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 77,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 78,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 79,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 80,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 81,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 82,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 83,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 84,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 85,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 86,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 87,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 88,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 89,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 90,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 91,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 92,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 93,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 94,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 95,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 96,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 97,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 98,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 99,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 100,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 101,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 102,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 103,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 104,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 105,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 106,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 107,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 108,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 109,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 110,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 111,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 112,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 113,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 114,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 115,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 116,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 117,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Room admin",
  },
  {
    id: 118,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 119,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
  {
    id: 120,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 121,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 122,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 123,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 124,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 125,
    displayName: "Martin Ralphs",
    email: "rmartin@gmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 126,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 127,
    displayName: "Imiller Imiller",
    email: "imiller@hotmail.com",
    dublicate: "—",
    type: "Power user",
  },
  {
    id: 128,
    displayName: "Whill Whill",
    email: "whill@outlook.com",
    dublicate: "—",
    type: "Docspace admin",
  },
];
