export const enum ThemeId {
  IconWrapper = "iconWrapper",
  IconButton = "iconButton",
  IconButtonPin = "iconButtonPin",
  IconButtonMute = "iconButtonMute",
  IndicatorFilterButton = "indicatorFilterButton",
  FilterBlockItemTag = "filterBlockItemTag",
  VersionBadge = "versionBadge",
  LinkForgotPassword = "linkForgotPassword",
  LoadingButton = "loadingButton",
  InfoPanelToggle = "infoPanelToggle",
  Link = "link",
  IndicatorLoader = "indicatorLoader",
  Progress = "progress",
  SubmenuText = "submenuText",
}
