/*
 * (c) Copyright Ascensio System SIA 2009-2025
 *
 * This program is a free software product.
 * You can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
 * Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
 * to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
 * any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
 * the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
 *
 * The  interactive user interfaces in modified source and object code versions of the Program must
 * display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product logo when
 * distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
 * trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
 * content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
 * International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 */

import {
  isFile,
  type TDownloadedFile,
  type TSortedDownloadFiles,
  type TSortedFiles,
} from "./DownloadDialog.types";

export const files: TDownloadedFile[] = [
  {
    shortWebUrl: "",
    access: 0,
    comment: "Uploaded",
    contentLength: "56.83 KB",
    created: "2025-01-20T12:23:50.0000000+01:00",
    createdBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    fileExst: ".docx",
    fileStatus: 0,
    fileType: 7,
    folderId: 6,
    id: 13,
    isFolder: false,
    isFile: true,
    denyDownload: false,
    denySharing: false,
    mute: false,
    pureContentLength: 58193,
    rootFolderType: 14,
    rootFolderId: 2,
    shared: true,
    title: "Document_1.docx",
    updated: "2025-03-04T16:00:00.0000000+01:00",
    updatedBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    version: 1,
    versionGroup: 1,
    viewUrl: "",
    webUrl: "",

    canShare: false,
    thumbnailStatus: 0,

    security: {
      Read: true,
      Download: true,
      Delete: false,
      Convert: false,
      Copy: false,
      CustomFilter: false,
      Duplicate: false,
      Edit: false,
      EditHistory: false,
      FillForms: false,
      Lock: false,
      Move: false,
      ReadHistory: false,
      Rename: false,
      Review: false,
      SubmitToFormGallery: false,
      Comment: false,
      CopyLink: false,
      CreateRoomFrom: false,
      EditForm: false,
      Embed: false,
    },
    viewAccessibility: {
      ImageView: false,
      MediaView: false,
      WebView: true,
      WebEdit: true,
      WebReview: true,
      WebCustomFilterEditing: false,
      WebRestrictedEditing: false,
      WebComment: true,
      CoAuhtoring: true,
      CanConvert: true,
      MustConvert: false,
    },
    isForm: false,
    checked: true,
    format: null,
    fileEntryType: 2,
  },
  {
    shortWebUrl: "",
    access: 0,
    comment: "The file is unlocked",
    contentLength: "136 KB",
    created: "2025-01-20T12:23:50.0000000+01:00",
    createdBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    fileExst: ".xlsx",
    fileStatus: 0,
    fileType: 5,
    folderId: 6,
    id: 34,
    isFolder: false,
    isFile: true,
    denyDownload: false,
    denySharing: false,
    mute: false,
    pureContentLength: 139264,
    rootFolderType: 14,
    rootFolderId: 2,
    shared: true,
    title: "Spreadsheet_1.xlsx",
    updated: "2025-03-05T12:07:19.0000000+01:00",
    updatedBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    version: 2,
    versionGroup: 2,
    viewUrl: "",
    webUrl: "",

    canShare: false,
    thumbnailStatus: 0,

    security: {
      Read: true,
      Download: true,
      Delete: false,
      Convert: false,
      Copy: false,
      CustomFilter: false,
      Duplicate: false,
      Edit: false,
      EditHistory: false,
      FillForms: false,
      Lock: false,
      Move: false,
      ReadHistory: false,
      Rename: false,
      Review: false,
      SubmitToFormGallery: false,
      Comment: false,
      CopyLink: false,
      CreateRoomFrom: false,
      EditForm: false,
      Embed: false,
    },
    viewAccessibility: {
      ImageView: false,
      MediaView: false,
      WebView: true,
      WebEdit: true,
      WebReview: false,
      WebCustomFilterEditing: true,
      WebRestrictedEditing: false,
      WebComment: true,
      CoAuhtoring: true,
      CanConvert: true,
      MustConvert: false,
    },
    isForm: false,
    checked: true,
    format: null,
    fileEntryType: 2,
  },
  {
    shortWebUrl: "",

    access: 0,
    comment: "Uploaded",
    contentLength: "56.83 KB",
    created: "2025-01-20T12:23:50.0000000+01:00",
    createdBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    fileExst: ".docx",
    fileStatus: 0,
    fileType: 7,
    folderId: 6,
    id: 12,
    isFolder: false,
    isFile: true,
    denyDownload: false,
    denySharing: false,
    mute: false,
    pureContentLength: 58193,
    rootFolderType: 14,
    rootFolderId: 2,
    shared: true,
    title: "Document_2.docx",
    updated: "2025-03-04T16:00:00.0000000+01:00",
    updatedBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    version: 1,
    versionGroup: 1,
    viewUrl: "",
    webUrl: "",

    canShare: false,
    thumbnailStatus: 0,

    security: {
      Read: true,
      Download: true,
      Delete: false,
      Convert: false,
      Copy: false,
      CustomFilter: false,
      Duplicate: false,
      Edit: false,
      EditHistory: false,
      FillForms: false,
      Lock: false,
      Move: false,
      ReadHistory: false,
      Rename: false,
      Review: false,
      SubmitToFormGallery: false,
      Comment: false,
      CopyLink: false,
      CreateRoomFrom: false,
      EditForm: false,
      Embed: false,
    },
    viewAccessibility: {
      ImageView: false,
      MediaView: false,
      WebView: true,
      WebEdit: true,
      WebReview: true,
      WebCustomFilterEditing: false,
      WebRestrictedEditing: false,
      WebComment: true,
      CoAuhtoring: true,
      CanConvert: true,
      MustConvert: false,
    },
    isForm: false,
    checked: true,
    format: null,
    fileEntryType: 2,
  },
  {
    shortWebUrl: "",

    access: 0,
    comment: "Uploaded",
    contentLength: "140.79 KB",
    created: "2025-01-20T12:23:50.0000000+01:00",
    createdBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    fileExst: ".xlsx",
    fileStatus: 0,
    fileType: 5,
    folderId: 6,
    id: 33,
    isFolder: false,
    isFile: true,
    denyDownload: false,
    denySharing: false,
    mute: false,
    pureContentLength: 144165,
    rootFolderType: 14,
    rootFolderId: 2,
    shared: true,
    title: "Spreadsheet_2.xlsx",
    updated: "2025-03-05T16:24:04.0000000+01:00",
    updatedBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
    },
    version: 1,
    versionGroup: 1,
    viewUrl: "",
    webUrl: "",

    canShare: false,
    thumbnailStatus: 0,

    security: {
      Read: true,
      Download: true,
      Delete: false,
      Convert: false,
      Copy: false,
      CustomFilter: false,
      Duplicate: false,
      Edit: false,
      EditHistory: false,
      FillForms: false,
      Lock: false,
      Move: false,
      ReadHistory: false,
      Rename: false,
      Review: false,
      SubmitToFormGallery: false,
      Comment: false,
      CopyLink: false,
      CreateRoomFrom: false,
      EditForm: false,
      Embed: false,
    },
    viewAccessibility: {
      ImageView: false,
      MediaView: false,
      WebView: true,
      WebEdit: true,
      WebReview: false,
      WebCustomFilterEditing: true,
      WebRestrictedEditing: false,
      WebComment: true,
      CoAuhtoring: true,
      CanConvert: true,
      MustConvert: false,
    },
    isForm: false,
    checked: true,
    format: null,
    fileEntryType: 2,
  },

  {
    shortWebUrl: "",

    access: 0,
    comment: "Uploaded",
    contentLength: "1.08 MB",
    created: "2025-01-20T12:23:50.0000000+01:00",
    createdBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatar: "",
      avatarOriginal: "",
      avatarMax: "",
      avatarMedium: "",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
      isAnonim: false,
    },
    fileExst: ".pptx",
    fileStatus: 0,
    fileType: 6,
    folderId: 6,
    id: 25,
    isFolder: false,
    mute: false,
    pureContentLength: 1132381,
    rootFolderType: 14,
    rootFolderId: 2,
    shared: true,
    title: "Presentation_1.pptx",
    updated: "2025-03-04T16:00:02.0000000+01:00",
    updatedBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatar: "",
      avatarOriginal: "",
      avatarMax: "",
      avatarMedium: "",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
      isAnonim: false,
    },
    version: 1,
    versionGroup: 1,
    viewUrl: "",
    webUrl: "",
    canShare: false,
    thumbnailStatus: 0,
    security: {
      Read: true,
      Comment: true,
      FillForms: false,
      Review: true,
      Edit: true,
      Delete: true,
      CustomFilter: true,
      Rename: true,
      ReadHistory: true,
      Lock: true,
      EditHistory: true,
      Copy: true,
      Move: true,
      Duplicate: true,
      SubmitToFormGallery: false,
      Download: true,
      Convert: true,
      CreateRoomFrom: false,
      CopyLink: true,
      Embed: true,
      EditForm: false,
    },
    viewAccessibility: {
      ImageView: false,
      MediaView: false,
      WebView: true,
      WebEdit: true,
      WebReview: false,
      WebCustomFilterEditing: false,
      WebRestrictedEditing: false,
      WebComment: true,
      CoAuhtoring: true,
      CanConvert: true,
      MustConvert: false,
    },
    isForm: false,
    checked: true,
    format: null,
    fileEntryType: 2,
  },
  {
    shortWebUrl: "",

    access: 0,
    comment: "Uploaded",
    contentLength: "1.08 MB",
    created: "2025-01-20T12:23:50.0000000+01:00",
    createdBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatar: "",
      avatarOriginal: "",
      avatarMax: "",
      avatarMedium: "",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
      isAnonim: false,
    },
    fileExst: ".pptx",
    fileStatus: 0,
    fileType: 6,
    folderId: 6,
    id: 26,
    isFolder: false,
    mute: false,
    pureContentLength: 1132381,
    rootFolderType: 14,
    rootFolderId: 2,
    shared: true,
    title: "Presentation_2.pptx",
    updated: "2025-03-04T16:00:02.0000000+01:00",
    updatedBy: {
      id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
      displayName: "Administrator ",
      avatar: "",
      avatarOriginal: "",
      avatarMax: "",
      avatarMedium: "",
      avatarSmall: "",
      profileUrl: "",
      hasAvatar: false,
      isAnonim: false,
    },
    version: 1,
    versionGroup: 1,
    viewUrl: "",
    webUrl: "",
    canShare: false,
    thumbnailStatus: 0,
    security: {
      Read: true,
      Comment: true,
      FillForms: false,
      Review: true,
      Edit: true,
      Delete: true,
      CustomFilter: true,
      Rename: true,
      ReadHistory: true,
      Lock: true,
      EditHistory: true,
      Copy: true,
      Move: true,
      Duplicate: true,
      SubmitToFormGallery: false,
      Download: true,
      Convert: true,
      CreateRoomFrom: false,
      CopyLink: true,
      Embed: true,
      EditForm: false,
    },
    viewAccessibility: {
      ImageView: false,
      MediaView: false,
      WebView: true,
      WebEdit: true,
      WebReview: false,
      WebCustomFilterEditing: false,
      WebRestrictedEditing: false,
      WebComment: true,
      CoAuhtoring: true,
      CanConvert: true,
      MustConvert: false,
    },
    isForm: false,
    checked: true,
    format: null,
    fileEntryType: 2,
  },
];

export const extsConvertible = {
  ".docx": [
    ".docm",
    ".dotm",
    ".dotx",
    ".epub",
    ".fb2",
    ".html",
    ".odt",
    ".ott",
    ".pdf",
    ".rtf",
    ".txt",
  ],
  ".pptx": [
    ".odp",
    ".otp",
    ".pdf",
    ".potm",
    ".potx",
    ".ppsm",
    ".ppsx",
    ".pptm",
  ],
  ".oform": [".pdf"],
  ".pdf": [
    ".docm",
    ".docx",
    ".dotm",
    ".dotx",
    ".epub",
    ".fb2",
    ".html",
    ".odt",
    ".ott",
    ".rtf",
    ".txt",
  ],
  ".xlsx": [".csv", ".ods", ".ots", ".pdf", ".xlsm", ".xltm", ".xltx"],
};

export const sortedFiles: TSortedFiles = {
  documents: files.filter((f) => isFile(f) && f.fileExst === ".docx"),
  spreadsheets: files.filter((f) => isFile(f) && f.fileExst === ".xlsx"),
  presentations: files.filter((f) => isFile(f) && f.fileExst === ".pptx"),
  diagrams: [],
  masterForms: [],
  pdfForms: [],
  other: [],
};

export const sortedPasswordFiles: TDownloadedFile[] = [files[0], files[1]];

export const sortedDownloadFiles: TSortedDownloadFiles = {
  password: [files[0]],
  other: [files[1]],
};

export const sortedDownloadFilesReadyToDownload: TSortedDownloadFiles = {
  password: [files[0]],
  remove: [files[1]],
  other: [],
};
