export enum AVAILABLE_CONTEXT_ITEMS {
  select = "select",
  open = "open",
  openPDF = "open-pdf",
  fillForm = "fill-form",
  edit = "edit",
  editPDF = "edit-pdf",
  preview = "preview",
  view = "view",
  pdfView = "pdf-view",
  copyLink = "link-for-room-members",
  download = "download",
  downloadAs = "download-as",
  markAsFavorite = "mark-as-favorite",
  removeFromFavorites = "remove-from-favorites",
  removeFromRecent = "remove-from-recent",
  share = "share",
  copy = "copy",
  duplicate = "duplicate",
  moveTo = "move-to",
  delete = "delete",
  deletePermanently = "delete-permanently",
  restore = "restore",
  rename = "rename",
}
