/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { describe, it, expect, vi } from "vitest";

// ---------------------------------------------------------------------------
// Pure-logic contract tests for the re-invite (showInviteIcon) visibility
// condition in PrivateMemberUser.
//
// The component shows a re-invite button when:
//   showInviteIcon = canInvite && isExpect
//
// Reference: packages/client/src/pages/Home/InfoPanel/Body/views/Members/
//            sub-components/User.tsx:101-103
//
// We test the boolean logic in isolation so the contract is enforced without
// requiring the full React component tree.
// ---------------------------------------------------------------------------

/**
 * Mirrors the showInviteIcon computation from PrivateMemberUser.
 * Any change to the component logic must be reflected here.
 */
function computeShowInviteIcon(
  canInvite: boolean,
  isExpect: boolean,
): boolean {
  return canInvite && isExpect;
}

// ---------------------------------------------------------------------------
// Scenario 1: icon is visible
// ---------------------------------------------------------------------------

describe("showInviteIcon — visible", () => {
  it("shows re-invite icon when canInvite=true AND isExpect=true", () => {
    expect(computeShowInviteIcon(true, true)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Scenario 2: icon is hidden
// ---------------------------------------------------------------------------

describe("showInviteIcon — hidden", () => {
  it("hides re-invite icon when canInvite=false (even if member is pending)", () => {
    expect(computeShowInviteIcon(false, true)).toBe(false);
  });

  it("hides re-invite icon when isExpect=false (member is active, even if canInvite)", () => {
    expect(computeShowInviteIcon(true, false)).toBe(false);
  });

  it("hides re-invite icon when both canInvite=false and isExpect=false", () => {
    expect(computeShowInviteIcon(false, false)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Scenario 3: isExpect derivation from activationStatus
// ---------------------------------------------------------------------------

// EmployeeActivationStatus values (mirrors packages/shared/enums/index.ts)
const EmployeeActivationStatus = {
  NotActivated: 0,
  Activated: 1,
  Pending: 2,
  AutoGenerated: 4,
} as const;

type ActivationStatusValue =
  (typeof EmployeeActivationStatus)[keyof typeof EmployeeActivationStatus];

/**
 * Mirrors the isExpect derivation in PrivateMembersView.tsx:
 *   isExpect = activationStatus === EmployeeActivationStatus.Pending
 */
function deriveIsExpect(activationStatus: ActivationStatusValue): boolean {
  return activationStatus === EmployeeActivationStatus.Pending;
}

describe("isExpect derivation from activationStatus", () => {
  it("is true when activationStatus is Pending (2)", () => {
    expect(deriveIsExpect(EmployeeActivationStatus.Pending)).toBe(true);
  });

  it("is false when activationStatus is Activated (1)", () => {
    expect(deriveIsExpect(EmployeeActivationStatus.Activated)).toBe(false);
  });

  it("is false when activationStatus is NotActivated (0)", () => {
    expect(deriveIsExpect(EmployeeActivationStatus.NotActivated)).toBe(false);
  });

  it("is false when activationStatus is AutoGenerated (4)", () => {
    expect(deriveIsExpect(EmployeeActivationStatus.AutoGenerated)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Scenario 4: re-invite handler toast contract
// ---------------------------------------------------------------------------

describe("onRepeatInvitation — toast contract", () => {
  const SUCCESS_KEY = "Common:RoomSuccessSentMultipleInvitatios";

  it("calls toastr.success with the correct key on successful resend", async () => {
    const toastrSuccess = vi.fn<[string], void>();
    const toastrError = vi.fn<[unknown], void>();
    const resendEmailInvitations = vi
      .fn()
      .mockResolvedValue(undefined);
    const t = (key: string) => key;

    // Inline the handler logic from PrivateMemberUser
    await resendEmailInvitations(1, true)
      .then(() => toastrSuccess(t(SUCCESS_KEY)))
      .catch((err: unknown) => toastrError(err));

    expect(toastrSuccess).toHaveBeenCalledOnce();
    expect(toastrSuccess).toHaveBeenCalledWith(SUCCESS_KEY);
    expect(toastrError).not.toHaveBeenCalled();
  });

  it("calls toastr.error when the resend API call rejects", async () => {
    const toastrSuccess = vi.fn<[string], void>();
    const toastrError = vi.fn<[unknown], void>();
    const apiError = new Error("network error");
    const resendEmailInvitations = vi
      .fn()
      .mockRejectedValue(apiError);
    const t = (key: string) => key;

    await resendEmailInvitations(1, true)
      .then(() => toastrSuccess(t(SUCCESS_KEY)))
      .catch((err: unknown) => toastrError(err));

    expect(toastrError).toHaveBeenCalledOnce();
    expect(toastrError).toHaveBeenCalledWith(apiError);
    expect(toastrSuccess).not.toHaveBeenCalled();
  });
});
