export const groups = [
  {
    id: 1,
    title: "Group 2",
    shortTitle: "G2",
    people: [
      {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        status: 1,
        activationStatus: 0,
        statusType: "unknown",
        role: "owner",
        isOwner: true,
        isAdmin: true,
        isCollaborator: false,
        isRoomAdmin: false,
        isVisitor: false,
        displayName: "Administrator ",
        avatar:
          "/storage/userPhotos/root/66faa6e4-f133-11ea-b126-00ffeec8b4ef_size_82-82.png?hash=959183592",
        hasAvatar: true,
        email: "nikitamushka@mail.ru",
        userName: "administrator",
        options: [
          "profile",
          "room-list",
          "separator-1",
          "change-name",
          "change-email",
          "change-password",
          "separator-2",
          "change-owner",
        ],
        firstName: "Administrator",
        lastName: "",
        isSSO: false,
      },
      {
        id: "9e3c0315-a96f-4992-ab84-93f2cc5ebd2f",
        status: 1,
        activationStatus: 0,
        statusType: "unknown",
        role: "user",
        isOwner: false,
        isAdmin: false,
        isCollaborator: false,
        isRoomAdmin: false,
        isVisitor: true,
        displayName: "asd asd",
        avatar:
          "http://192.168.0.105/static/images/default_user_photo_size_32-32.png?hash=92dc10350832b51cfbc1",
        hasAvatar: false,
        email: "asd@asd.asd",
        userName: "asd",
        options: [
          "details",
          "room-list",
          "separator-1",
          "change-email",
          "change-password",
          "reset-auth",
          "separator-2",
          "disable",
        ],
        firstName: "asd",
        lastName: "asd",
        isSSO: false,
      },
    ],
  },
  {
    id: 0,
    title: "Group 1",
    shortTitle: "G1",
    people: [
      {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        status: 1,
        activationStatus: 0,
        statusType: "unknown",
        role: "owner",
        isOwner: true,
        isAdmin: true,
        isCollaborator: false,
        isRoomAdmin: false,
        isVisitor: false,
        displayName: "Administrator ",
        avatar:
          "/storage/userPhotos/root/66faa6e4-f133-11ea-b126-00ffeec8b4ef_size_82-82.png?hash=959183592",
        hasAvatar: true,
        email: "nikitamushka@mail.ru",
        userName: "administrator",
        options: [
          "profile",
          "room-list",
          "separator-1",
          "change-name",
          "change-email",
          "change-password",
          "separator-2",
          "change-owner",
        ],
        firstName: "Administrator",
        lastName: "",
        isSSO: false,
      },
      {
        id: "9e3c0315-a96f-4992-ab84-93f2cc5ebd2f",
        status: 1,
        activationStatus: 0,
        statusType: "unknown",
        role: "user",
        isOwner: false,
        isAdmin: false,
        isCollaborator: false,
        isRoomAdmin: false,
        isVisitor: true,
        displayName: "asd asd",
        avatar:
          "http://192.168.0.105/static/images/default_user_photo_size_32-32.png?hash=92dc10350832b51cfbc1",
        hasAvatar: false,
        email: "asd@asd.asd",
        userName: "asd",
        options: [
          "details",
          "room-list",
          "separator-1",
          "change-email",
          "change-password",
          "reset-auth",
          "separator-2",
          "disable",
        ],
        firstName: "asd",
        lastName: "asd",
        isSSO: false,
      },
    ],
  },
];
