const path = require("path");
const sharedConfig = require("../shared/eslint.config.js");

module.exports = [
  ...sharedConfig,
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.eslint.json",
        tsconfigRootDir: __dirname,
        sourceType: "module",
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-expressions": "off",
    },
    settings: {
      "import/resolver": {
        webpack: {
          config: {
            resolve: {
              extensions: [".jsx", ".js", ".tsx", ".ts", ".json"],
              alias: {
                PUBLIC_DIR: path.resolve(__dirname, "../../public"),
                ASSETS_DIR: path.resolve(__dirname, "./public"),
                "@": path.resolve(__dirname, "./src"),
                PACKAGE_FILE: path.resolve(__dirname, "package.json"),
              },
            },
          },
        },
      },
    },
  },
  {
    ignores: [
      "./tsconfig.json",
      "./eslint.config.js",
      "node_modules/**",
      ".next/**",
      "coverage/**",
      "storybook-static/**",
      "*/**/autoGeneratedTranslations.js",
      "*/**/autoGeneratedTranslations.ts",
      "webpack.config.js",
      "tests/**/*",
    ],
  },
];
