import i18n from "i18next";
import { initReactI18next } from "react-i18next";

import config from "../../../../../buildtools/config/appsettings.json";

import { getLtrLanguageForEditor } from "@docspace/shared/utils/common";

import { translations } from "./autoGeneratedTranslations";

export const getI18NInstance = (lng: string, portalLng: string) => {
  if (typeof window === "undefined") return;

  const currentLng = getLtrLanguageForEditor(lng, portalLng, true);

  // const cultures = config.web.cultures.split(",");

  i18n.use(initReactI18next).init({
    lng: currentLng,
    fallbackLng: "en",
    load: "currentOnly",

    debug: false,

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
      format: function (value, format) {
        if (format === "lowercase") return value.toLowerCase();
        return value;
      },
    },

    ns: ["Editor", "Common", "DeepLink"],
    defaultNS: "Editor",

    react: {
      useSuspense: false,
    },
  });

  Array.from(translations).forEach(([lng, nsList]) => {
    Array.from(nsList).forEach(([ns, obj]) => {
      i18n.addResourceBundle(lng, ns, obj, true, true);
    });
  });

  return i18n;
};
