/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { getLanguage } from "@docspace/shared/utils";
import { translations } from "./autoGeneratedTranslations";

// Resolve every namespace of a language to a single bundle file
// (`/locales/{lng}/_combined.json`) so i18next loads all translations in one
// request. Used together with the backend's `combinedNamespaces` option.
// The bundle is produced at build time by the copy-locales plugin.
export function loadCombinedLanguagePath() {
  return (lng) => {
    const language = getLanguage(lng instanceof Array ? lng[0] : lng);
    const url = `/locales/${language}/_combined.json`;
    // The combined bundle URL is fixed and served `immutable, max-age=1y`, so
    // append a content hash (baked in at build time) to bust the cache when
    // translations change. COMBINED_LOCALE_HASHES is injected via Vite define.
    const hash =
      typeof COMBINED_LOCALE_HASHES !== "undefined"
        ? COMBINED_LOCALE_HASHES[language]
        : undefined;
    return hash ? `${url}?hash=${hash}` : url;
  };
}

export function loadLanguagePath(homepage, fixedNS = null) {
  return (lng, ns) => {
    const language = getLanguage(lng instanceof Array ? lng[0] : lng);

    const lngCollection = translations?.get(language);

    const data = lngCollection?.get(`${fixedNS || ns}`);

    if (!data) return `/locales/${language}/${fixedNS || ns}.json`;

    let path = data?.split("/");
    const length = path?.length;

    const isCommonPath = path[length - 1].indexOf("Common") > -1;

    path = `/${path[length - 3]}/${path[length - 2]}/${path[length - 1]}`;

    if (ns.length > 0 && ns[0] === "Common" && isCommonPath) {
      return `/static${path}`;
    }

    return path;
  };
}
