import { getLanguage } from "@docspace/shared/utils";
import { translations } from "./autoGeneratedTranslations";

// Resolve every namespace of a language to a single bundle file
// (`/locales/{lng}/_combined.json`) so i18next loads all translations in one
// request. Used together with the backend's `combinedNamespaces` option.
// The bundle is produced at build time by the copy-locales plugin.
export function loadCombinedLanguagePath() {
  return (lng) => {
    const language = getLanguage(lng instanceof Array ? lng[0] : lng);
    return `/locales/${language}/_combined.json`;
  };
}

export function loadLanguagePath(homepage, fixedNS = null) {
  return (lng, ns) => {
    const language = getLanguage(lng instanceof Array ? lng[0] : lng);

    const lngCollection = translations?.get(language);

    const data = lngCollection?.get(`${fixedNS || ns}`);

    if (!data) return `/locales/${language}/${fixedNS || ns}.json`;

    let path = data?.split("/");
    const length = path?.length;

    const isCommonPath = path[length - 1].indexOf("Common") > -1;

    path = `/${path[length - 3]}/${path[length - 2]}/${path[length - 1]}`;

    if (ns.length > 0 && ns[0] === "Common" && isCommonPath) {
      return `/static${path}`;
    }

    return path;
  };
}
