import path from "path";
import sharedConfig from "../shared/eslint.config.js";

export default [
  ...sharedConfig,
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.eslint.json",
        tsconfigRootDir: import.meta.dirname,
        sourceType: "module",
      },
    },
    rules: {
      "@next/next/no-img-element": "off",
      "import/extensions": [
        "error",
        "ignorePackages",
        {
          js: "never",
          jsx: "never",
          ts: "never",
          tsx: "never",
        },
      ],
      "no-console": "off",
      "no-continue": "off",
      "no-fallthrough": "off",
      "no-await-in-loop": "off",
      "no-useless-escape": "off",
      "react/no-danger": "off",
      "@typescript-eslint/naming-convention": "off",
      "jsx-a11y/aria-role": "off",
      "react/no-unescaped-entities": "off",
      "no-plusplus": "off",
      "no-bitwise": "off",
      eqeqeq: "off",
      "@typescript-eslint/no-explicit-any": "off",
      "react/forbid-prop-types": "off",
      "class-methods-use-this": "off",
      "@typescript-eslint/no-loop-func": "off",
      "react/prop-types": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "jsx-a11y/tabindex-no-positive": "off",
      "react-hooks/exhaustive-deps": "off",
      "react/function-component-definition": "off",
      "import/no-named-as-default": "off",
      "global-require": "off",
    },
    settings: {
      "import/resolver": {
        webpack: {
          config: {
            resolve: {
              extensions: [".jsx", ".js", ".tsx", ".ts", ".json"],
              alias: {
                PUBLIC_DIR: path.resolve(import.meta.dirname, "../../public"),
                ASSETS_DIR: path.resolve(import.meta.dirname, "./public"),
                "@": path.resolve(import.meta.dirname, "./src"),
                PACKAGE_FILE: path.resolve(import.meta.dirname, "package.json"),
              },
            },
          },
        },
      },
    },
  },
  {
    ignores: [
      "./tsconfig.json",
      "coverage/**",
      "storybook-static/**",
      "*/**/autoGeneratedTranslations.js",
      "*/**/autoGeneratedTranslations.ts",
      "webpack.config.js",
      "tests/**/*",
    ],
  },
];
