//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Migration.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MigrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Migration.Core.Resources.MigrationResource", typeof(MigrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing temporary data.
        /// </summary>
        public static string ClearingTemporaryData {
            get {
                return ResourceManager.GetString("ClearingTemporaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing....
        /// </summary>
        public static string DataProcessing {
            get {
                return ResourceManager.GetString("DataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing completed.
        /// </summary>
        public static string DataProcessingCompleted {
            get {
                return ResourceManager.GetString("DataProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database parsing.
        /// </summary>
        public static string DumpParse {
            get {
                return ResourceManager.GetString("DumpParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail`s Contacts.
        /// </summary>
        public static string GoogleModuleNameContacts {
            get {
                return ResourceManager.GetString("GoogleModuleNameContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive`s Files.
        /// </summary>
        public static string GoogleModuleNameDocuments {
            get {
                return ResourceManager.GetString("GoogleModuleNameDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group migration {0} ({1}/{2}).
        /// </summary>
        public static string GroupMigration {
            get {
                return ResourceManager.GetString("GroupMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating user contacts {0} ({1}/{2}).
        /// </summary>
        public static string MigratingUserContacts {
            get {
                return ResourceManager.GetString("MigratingUserContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating user files {0} ({1}/{2}).
        /// </summary>
        public static string MigratingUserFiles {
            get {
                return ResourceManager.GetString("MigratingUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration canceled.
        /// </summary>
        public static string MigrationCanceled {
            get {
                return ResourceManager.GetString("MigrationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed.
        /// </summary>
        public static string MigrationCompleted {
            get {
                return ResourceManager.GetString("MigrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while initializing {0} migrator.
        /// </summary>
        public static string MigrationInitException {
            get {
                return ResourceManager.GetString("MigrationInitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such migration provider.
        /// </summary>
        public static string MigrationNotFoundException {
            get {
                return ResourceManager.GetString("MigrationNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration is in progress.
        /// </summary>
        public static string MigrationProgressException {
            get {
                return ResourceManager.GetString("MigrationProgressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing is still in progress.
        /// </summary>
        public static string MigrationStartException {
            get {
                return ResourceManager.GetString("MigrationStartException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration is already in progress.
        /// </summary>
        public static string MigrationUploadException {
            get {
                return ResourceManager.GetString("MigrationUploadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string ModuleNameCalendar {
            get {
                return ResourceManager.GetString("ModuleNameCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string ModuleNameGroups {
            get {
                return ResourceManager.GetString("ModuleNameGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string ModuleNameMail {
            get {
                return ResourceManager.GetString("ModuleNameMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string ModuleNameUsers {
            get {
                return ResourceManager.GetString("ModuleNameUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string NextcloudModuleNameContacts {
            get {
                return ResourceManager.GetString("NextcloudModuleNameContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User`s Files.
        /// </summary>
        public static string NextcloudModuleNameDocuments {
            get {
                return ResourceManager.GetString("NextcloudModuleNameDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string OnlyofficeModuleNameCalendar {
            get {
                return ResourceManager.GetString("OnlyofficeModuleNameCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string OnlyofficeModuleNameDocuments {
            get {
                return ResourceManager.GetString("OnlyofficeModuleNameDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string OnlyofficeModuleNameMail {
            get {
                return ResourceManager.GetString("OnlyofficeModuleNameMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string OnlyofficeModuleNamePeople {
            get {
                return ResourceManager.GetString("OnlyofficeModuleNamePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for migration.
        /// </summary>
        public static string PreparingForMigration {
            get {
                return ResourceManager.GetString("PreparingForMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting data processing....
        /// </summary>
        public static string StartOfDataProcessing {
            get {
                return ResourceManager.GetString("StartOfDataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping....
        /// </summary>
        public static string Unzipping {
            get {
                return ResourceManager.GetString("Unzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipping completed....
        /// </summary>
        public static string UnzippingFinished {
            get {
                return ResourceManager.GetString("UnzippingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User calendar migration {0} ({1}/{2}).
        /// </summary>
        public static string UserCalendarMigration {
            get {
                return ResourceManager.GetString("UserCalendarMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User migration {0} ({1}/{2}).
        /// </summary>
        public static string UserMigration {
            get {
                return ResourceManager.GetString("UserMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import user: {0} ({1}/{2}).
        /// </summary>
        public static string UserSkipped {
            get {
                return ResourceManager.GetString("UserSkipped", resourceCulture);
            }
        }
    }
}
