/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// =============================================================================
// Deterministic crypto fixture for (private) e2e tests.
//
// Contains a pre-serialized identity envelope encrypted under a fixed
// passphrase. The envelope is a valid DSEK v2 identity (X25519 keypair,
// passphrase-protected with argon2id, AES-256-GCM).
//
// HOW THE ENVELOPE WAS GENERATED
// --------------------------------
// Run the one-off generator in packages/sdk/__tests__/e2e/fixtures/gen-crypto.mjs
// (in packages/shared where hash-wasm is available):
//
//   node --input-type=module < packages/sdk/__tests__/e2e/fixtures/gen-crypto.mjs
//
// The generator uses:
//   - WebCrypto X25519 generateKey() for a fresh keypair
//   - argon2id FAST_PARAMS (m_KiB=256, t=1, p=1) — intentionally lightweight
//     so unlockWithPassphrase runs in <500ms inside Playwright/Chromium
//   - Fixed salt: 0xaabbccddeeff112233445566778899_00
//   - Fixed IV:   0xdeadbeefcafebabe001122_33
//   - Passphrase: FIXTURE_PASSPHRASE
//
// IMPORTANT: These are TEST-ONLY values. Never use them in production.
// The private key inside the envelope is unique to this fixture run
// (generated at fixture-creation time, then embedded as a constant).
//
// To regenerate:
//   1. node --input-type=module < gen-crypto.mjs
//   2. Replace FIXTURE_PUBLIC_KEY and FIXTURE_PRIVATE_KEY_ENC below.
//   3. Re-run `npx playwright test __tests__/e2e/private` to verify.
// =============================================================================

import type { TEncryptionKeyPair } from "@docspace/shared/api/privacy/types";

/** The passphrase used to unlock the fixture identity in tests. */
export const FIXTURE_PASSPHRASE = "test-passphrase-12345";

/**
 * The user ID used by the fixture identity and all MSW handlers.
 * Matches the `successSelf.id` in packages/shared/__mocks__/handlers/people/self.ts.
 */
export const FIXTURE_USER_ID = "66faa6e4-f133-11ea-b126-00ffeec8b4ef";

/**
 * Pre-serialized identity envelope encrypted under FIXTURE_PASSPHRASE.
 *
 * Format: DSEK v2 — magic(4) + version(1) + suite(1) + flags(1) + pubkey(32)
 *         + passphrase_slot(3+4+16+12+48)
 *
 * Generated by gen-crypto.mjs with FAST_PARAMS (m=256, t=1, p=1) so that
 * argon2id inside Chromium (via hash-wasm WASM) completes quickly during tests.
 */
export const FIXTURE_IDENTITY: TEncryptionKeyPair = {
  id: FIXTURE_USER_ID,
  userId: FIXTURE_USER_ID,
  // Raw X25519 public key (32 bytes, base64-encoded)
  publicKey: "7Z0+pucnAeMvsN1f6tHmBaSA2HAQzr+FH1dXKbVV8WU=",
  // Full DSEK envelope: the private key is encrypted with AES-256-GCM under
  // the KEK derived from FIXTURE_PASSPHRASE via argon2id FAST_PARAMS.
  privateKeyEnc:
    "RFNFSwIBAO2dPqbnJwHjL7DdX+rR5gWkgNhwEM6/hR9XVym1VfFlAQEBAAABAKq7zN3u/xEiM0RVZneImQDerb7vyv66vgARIjPBMEfKMMZAU+6dxw8T1RcWGHxuQ9g4NiZyxzM7n+8bxBA5EQuPmsExLbrv6HJQ9lA=",
  date: "2026-01-01T00:00:00.000Z",
  cryptoEngineId: "DSEK-v2-X25519-HKDF-AES256GCM",
};

/**
 * The canonical `SerializedIdentity` shape expected by `unlockWithPassphrase`.
 * Use this as the response body for GET /api/2.0/privacyroom/keys in tests
 * that need a pre-unlocked or lockable identity state.
 */
export const FIXTURE_SERIALIZED_IDENTITY = {
  publicKey: FIXTURE_IDENTITY.publicKey,
  privateKeyEnc: FIXTURE_IDENTITY.privateKeyEnc,
};

/**
 * Argon2id parameters used to encrypt the fixture envelope.
 * Intentionally lightweight (m=256 KiB, t=1, p=1) so that
 * unlockWithPassphrase completes in < 500ms inside Playwright/Chromium.
 * Production uses DEFAULT_ARGON2_PARAMS (m=65536, t=3, p=4).
 */
export const FIXTURE_ARGON2_PARAMS = {
  m_KiB: 256,
  t: 1,
  p: 1,
} as const;
