// (c) Copyright Ascensio System SIA 2009-2024
//
// This program is a free software product.
// You can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
// Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
// to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
// any third-party rights.
//
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
// the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
//
// You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
//
// The  interactive user interfaces in modified source and object code versions of the Program must
// display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
//
// Pursuant to Section 7(b) of the License you must retain the original Product logo when
// distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
// trademark law for use of our trademarks.
//
// All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
// content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
// International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode

import { settingsTree } from "./settingsTree";
import { translations } from "../autoGeneratedTranslations";
import i18n from "../i18n";

export const getItemByLink = (path: string) => {
  const arrayPath = path.split("/");
  const resultPath = arrayPath[arrayPath.length - 1];
  const item = settingsTree.filter((item) => item.link === resultPath);
  return item[0];
};

export const getMinifyTitle = (title: string) => {
  const titleArr = title.split(" ");

  if (titleArr.length === 1) {
    return titleArr[0][0].toUpperCase();
  }
  const firstChar = titleArr[0][0].toUpperCase();
  const secondChar = titleArr[1][0].toUpperCase();
  return `${firstChar}${secondChar}`;
};

export function getLanguage(lng: string) {
  try {
    let language = lng == "en-US" || lng == "en-GB" ? "en" : lng;

    const splitted = lng.split("-");

    if (splitted.length == 2 && splitted[0] == splitted[1].toLowerCase()) {
      language = splitted[0];
    }

    return language;
  } catch (error) {
    console.error(error);
  }

  return lng;
}

export function loadLanguagePath(homepage: string, fixedNS = null) {
  return (lng: string | [string], ns: string) => {
    const language = getLanguage(lng instanceof Array ? lng[0] : lng);

    const lngCollection = translations.get(language);

    const path = lngCollection?.get(`${fixedNS || ns}`);

    if (!path) return `/management/locales/${language}/${fixedNS || ns}.json`;

    const isCommonPath = path?.indexOf("Common") > -1;
    const isClientPath = !isCommonPath && path?.indexOf("Management") === -1;

    if (ns.length > 0 && ns[0] === "Common" && isCommonPath) {
      return path.replace("/management/", "/static/");
    }

    if (ns.length > 0 && ns[0] != "Management" && isClientPath) {
      return path.replace("/management/", "/");
    }

    return path;
  };
}

export const setDocumentTitle = (subTitle = null) => {
  let title;

  // const currentModule = this.settingsStore?.product;
  const organizationName = i18n.t("Common:OrganizationName");

  if (subTitle) {
    title = `${subTitle} - ${organizationName}`;
    // if (this.isAuthenticated && currentModule) {
    //   title = `${subTitle} - ${currentModule.title}`;
    // } else {
    //   title = `${subTitle} - ${organizationName}`;
    // }
    // } else if ( organizationName) {
    // title = `${currentModule.title} - ${organizationName}`;
  } else {
    title = organizationName;
  }

  document.title = title ?? "";
};
