/*
 * (c) Copyright Ascensio System SIA 2009-2025
 *
 * This program is a free software product.
 * You can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
 * Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
 * to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
 * any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
 * the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
 *
 * The  interactive user interfaces in modified source and object code versions of the Program must
 * display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product logo when
 * distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
 * trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
 * content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
 * International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 */

import { TFilesSettings } from "../../../../api/files/types";

const getFilesSettings = (): TFilesSettings => {
  return {
    extsImagePreviewed: [
      ".svg",
      ".bmp",
      ".gif",
      ".jpeg",
      ".jpg",
      ".png",
      ".ico",
      ".tif",
      ".tiff",
      ".webp",
      ".heic",
    ],
    extsMediaPreviewed: [
      ".aac",
      ".flac",
      ".m4a",
      ".mp3",
      ".oga",
      ".ogg",
      ".wav",
      ".f4v",
      ".m4v",
      ".mov",
      ".mp4",
      ".ogv",
      ".webm",
    ],
    extsWebPreviewed: [
      ".csv",
      ".djvu",
      ".doc",
      ".docm",
      ".docx",
      ".docxf",
      ".dot",
      ".dotm",
      ".dotx",
      ".dps",
      ".dpt",
      ".epub",
      ".et",
      ".ett",
      ".fb2",
      ".fodp",
      ".fods",
      ".fodt",
      ".gdoc",
      ".gsheet",
      ".gslides",
      ".htm",
      ".html",
      ".mht",
      ".mhtml",
      ".odp",
      ".ods",
      ".odt",
      ".oform",
      ".otp",
      ".ots",
      ".ott",
      ".oxps",
      ".pdf",
      ".pot",
      ".potm",
      ".potx",
      ".pps",
      ".ppsm",
      ".ppsx",
      ".ppt",
      ".pptm",
      ".pptx",
      ".rtf",
      ".stw",
      ".sxc",
      ".sxi",
      ".sxw",
      ".txt",
      ".wps",
      ".wpt",
      ".xls",
      ".xlsb",
      ".xlsm",
      ".xlsx",
      ".xlt",
      ".xltm",
      ".xltx",
      ".xml",
      ".xps",
    ],
    extsWebEdited: [
      ".csv",
      ".doc",
      ".docm",
      ".docx",
      ".docxf",
      ".dot",
      ".dotm",
      ".dotx",
      ".dps",
      ".dpt",
      ".epub",
      ".et",
      ".ett",
      ".fb2",
      ".fodp",
      ".fods",
      ".fodt",
      ".htm",
      ".html",
      ".mht",
      ".mhtml",
      ".odp",
      ".ods",
      ".odt",
      ".oform",
      ".otp",
      ".ots",
      ".ott",
      ".pdf",
      ".pot",
      ".potm",
      ".potx",
      ".pps",
      ".ppsm",
      ".ppsx",
      ".ppt",
      ".pptm",
      ".pptx",
      ".rtf",
      ".stw",
      ".sxc",
      ".sxi",
      ".sxw",
      ".txt",
      ".wps",
      ".wpt",
      ".xls",
      ".xlsb",
      ".xlsm",
      ".xlsx",
      ".xlt",
      ".xltm",
      ".xltx",
      ".xml",
    ],
    extsWebEncrypt: [
      ".docm",
      ".docx",
      ".docxf",
      ".dotm",
      ".dotx",
      ".oform",
      ".potm",
      ".potx",
      ".ppsm",
      ".pptm",
      ".ppsx",
      ".pptx",
      ".xlsm",
      ".xlsx",
      ".xltm",
      ".xltx",
      ".pdf",
    ],
    extsWebReviewed: [".docm", ".docx", ".docxf", ".dotm", ".dotx"],
    extsWebCustomFilterEditing: [".xlsm", ".xlsx", ".xltm", ".xltx"],
    extsWebRestrictedEditing: [".pdf"],
    extsWebCommented: [
      ".docm",
      ".docx",
      ".docxf",
      ".dotm",
      ".dotx",
      ".potm",
      ".potx",
      ".ppsm",
      ".pptm",
      ".ppsx",
      ".pptx",
      ".xlsm",
      ".xlsx",
      ".xltm",
      ".xltx",
      ".pdf",
    ],
    extsWebTemplate: [],
    extsCoAuthoring: [
      ".csv",
      ".docm",
      ".docx",
      ".docxf",
      ".dotm",
      ".dotx",
      ".oform",
      ".pdf",
      ".potm",
      ".potx",
      ".ppsm",
      ".pptm",
      ".ppsx",
      ".pptx",
      ".txt",
      ".xlsm",
      ".xlsx",
      ".xltm",
      ".xltx",
    ],
    extsMustConvert: [
      ".doc",
      ".dot",
      ".dps",
      ".dpt",
      ".epub",
      ".et",
      ".ett",
      ".fb2",
      ".fodp",
      ".fods",
      ".fodt",
      ".htm",
      ".html",
      ".mht",
      ".mhtml",
      ".odp",
      ".ods",
      ".odt",
      ".otp",
      ".ots",
      ".ott",
      ".pot",
      ".pps",
      ".ppt",
      ".rtf",
      ".stw",
      ".sxc",
      ".sxi",
      ".sxw",
      ".wps",
      ".wpt",
      ".xls",
      ".xlsb",
      ".xlt",
      ".xml",
    ],
    extsConvertible: {
      ".pptt": [".pptx"],
      ".mht": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".docm": [
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".docx": [
        ".docm",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".html": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".otp": [
        ".odp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".doc": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".wpt": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xltm": [".csv", ".ods", ".ots", ".pdf", ".xlsm", ".xlsx", ".xltx"],
      ".ods": [".csv", ".ots", ".pdf", ".xlsm", ".xlsx", ".xltm", ".xltx"],
      ".et": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".dps": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".pptm": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptx",
      ],
      ".potx": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".xlsm": [".csv", ".ods", ".ots", ".pdf", ".xlsx", ".xltm", ".xltx"],
      ".pptx": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
      ],
      ".ppsm": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".ots": [".csv", ".ods", ".pdf", ".xlsm", ".xlsx", ".xltm", ".xltx"],
      ".xlt": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".ppsx": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".pptm",
        ".pptx",
      ],
      ".doct": [".docx"],
      ".dotm": [
        ".docm",
        ".docx",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".pot": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".sxi": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".dpt": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".rtf": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".txt",
      ],
      ".oform": [".pdf"],
      ".sxc": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".fods": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".sxw": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xlsb": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".djvu": [".pdf"],
      ".pps": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".stw": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xls": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".txt": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
      ],
      ".pdf": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".rtf",
        ".txt",
      ],
      ".xltx": [".csv", ".ods", ".ots", ".pdf", ".xlsm", ".xlsx", ".xltm"],
      ".fodp": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".potm": [
        ".odp",
        ".otp",
        ".pdf",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".mhtml": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xml": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xlsx": [".csv", ".ods", ".ots", ".pdf", ".xlsm", ".xltm", ".xltx"],
      ".dotx": [
        ".docm",
        ".docx",
        ".dotm",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".ppt": [
        ".odp",
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".docxf": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".odt": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".csv": [".ods", ".ots", ".pdf", ".xlsm", ".xlsx", ".xltm", ".xltx"],
      ".wps": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".fodt": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".epub": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".oxps": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xps": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".ett": [
        ".csv",
        ".ods",
        ".ots",
        ".pdf",
        ".xlsm",
        ".xlsx",
        ".xltm",
        ".xltx",
      ],
      ".ott": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".xlst": [".xlsx"],
      ".dot": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".odp": [
        ".otp",
        ".pdf",
        ".potm",
        ".potx",
        ".ppsm",
        ".ppsx",
        ".pptm",
        ".pptx",
      ],
      ".fb2": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
      ".htm": [
        ".docm",
        ".docx",
        ".dotm",
        ".dotx",
        ".epub",
        ".fb2",
        ".html",
        ".odt",
        ".ott",
        ".pdf",
        ".rtf",
        ".txt",
      ],
    },
    extsUploadable: [
      ".csv",
      ".djvu",
      ".doc",
      ".docm",
      ".docx",
      ".docxf",
      ".dot",
      ".dotm",
      ".dotx",
      ".dps",
      ".dpt",
      ".epub",
      ".et",
      ".ett",
      ".fb2",
      ".fodp",
      ".fods",
      ".fodt",
      ".gdoc",
      ".gsheet",
      ".gslides",
      ".htm",
      ".html",
      ".mht",
      ".mhtml",
      ".odp",
      ".ods",
      ".odt",
      ".oform",
      ".otp",
      ".ots",
      ".ott",
      ".oxps",
      ".pdf",
      ".pot",
      ".potm",
      ".potx",
      ".pps",
      ".ppsm",
      ".ppsx",
      ".ppt",
      ".pptm",
      ".pptx",
      ".rtf",
      ".stw",
      ".sxc",
      ".sxi",
      ".sxw",
      ".txt",
      ".wps",
      ".wpt",
      ".xls",
      ".xlsb",
      ".xlsm",
      ".xlsx",
      ".xlt",
      ".xltm",
      ".xltx",
      ".xml",
      ".xps",
      ".svg",
      ".bmp",
      ".gif",
      ".jpeg",
      ".jpg",
      ".png",
      ".ico",
      ".tif",
      ".tiff",
      ".webp",
      ".heic",
    ],
    extsArchive: [
      ".zip",
      ".rar",
      ".ace",
      ".arc",
      ".arj",
      ".bh",
      ".cab",
      ".enc",
      ".gz",
      ".ha",
      ".jar",
      ".lha",
      ".lzh",
      ".pak",
      ".pk3",
      ".tar",
      ".tgz",
      ".gz",
      ".uu",
      ".uue",
      ".xxe",
      ".z",
      ".zoo",
    ],
    extsVideo: [
      ".3gp",
      ".asf",
      ".avi",
      ".f4v",
      ".fla",
      ".flv",
      ".m2ts",
      ".m4v",
      ".mkv",
      ".mov",
      ".mp4",
      ".mpeg",
      ".mpg",
      ".mts",
      ".ogv",
      ".svi",
      ".vob",
      ".webm",
      ".wmv",
    ],
    extsAudio: [
      ".aac",
      ".ac3",
      ".aiff",
      ".amr",
      ".ape",
      ".cda",
      ".flac",
      ".m4a",
      ".mid",
      ".mka",
      ".mp3",
      ".mpc",
      ".oga",
      ".ogg",
      ".pcm",
      ".ra",
      ".raw",
      ".wav",
      ".wma",
    ],
    extsImage: [
      ".bmp",
      ".cod",
      ".gif",
      ".ief",
      ".jpe",
      ".jpeg",
      ".jpg",
      ".jfif",
      ".tiff",
      ".tif",
      ".cmx",
      ".ico",
      ".pnm",
      ".pbm",
      ".png",
      ".ppm",
      ".rgb",
      ".svg",
      ".xbm",
      ".xpm",
      ".xwd",
      ".svgt",
      ".svgy",
      ".gdraw",
      ".webp",
      ".heic",
    ],
    extsSpreadsheet: [
      ".xls",
      ".xlsx",
      ".xlsm",
      ".xlt",
      ".xltx",
      ".xltm",
      ".ods",
      ".fods",
      ".ots",
      ".csv",
      ".sxc",
      ".et",
      ".ett",
      ".xlst",
      ".xlsy",
      ".xlsb",
      ".gsheet",
    ],
    extsPresentation: [
      ".pps",
      ".ppsx",
      ".ppsm",
      ".ppt",
      ".pptx",
      ".pptm",
      ".pot",
      ".potx",
      ".potm",
      ".odp",
      ".fodp",
      ".otp",
      ".dps",
      ".dpt",
      ".sxi",
      ".pptt",
      ".ppty",
      ".gslides",
    ],
    extsDocument: [
      ".doc",
      ".docx",
      ".docm",
      ".dot",
      ".dotx",
      ".dotm",
      ".odt",
      ".fodt",
      ".ott",
      ".rtf",
      ".txt",
      ".html",
      ".htm",
      ".mht",
      ".mhtml",
      ".xml",
      ".pdf",
      ".djvu",
      ".fb2",
      ".epub",
      ".xps",
      ".oxps",
      ".sxw",
      ".stw",
      ".wps",
      ".wpt",
      ".doct",
      ".docy",
      ".gdoc",
      ".drawio",
      ".md",
      ".markdown",
    ],
    extsDiagram: [".vsdm", ".vsdx", ".vssm", ".vssx", ".vstm", ".vstx"],
    internalFormats: {
      Document: ".docx",
      Spreadsheet: ".xlsx",
      Presentation: ".pptx",
      Pdf: ".pdf",
    },
    masterFormExtension: ".docxf",
    paramVersion: "version",
    paramOutType: "outputtype",
    fileDownloadUrlString: "/filehandler.ashx?action=download&fileid={0}",
    fileWebViewerUrlString: "/doceditor?fileid={0}&action=view",
    fileWebViewerExternalUrlString:
      "/doceditor?fileuri={0}&title={1}&folderurl={2}",
    fileWebEditorUrlString: "/doceditor?fileid={0}",
    fileWebEditorExternalUrlString:
      "/filehandler.ashx?action=create&fileuri={0}&title={1}",
    fileRedirectPreviewUrlString: "/filehandler.ashx?action=redirect",
    fileThumbnailUrlString: "/filehandler.ashx?action=thumb&fileid={0}",
    confirmDelete: true,
    enableThirdParty: true,
    externalShare: true,
    externalShareSocialMedia: true,
    storeOriginalFiles: true,
    keepNewFileName: false,
    displayFileExtension: false,
    convertNotify: false,
    hideConfirmConvertSave: false,
    hideConfirmConvertOpen: false,
    defaultOrder: {
      is_asc: false,
      property: 0,
    },
    forcesave: true,
    storeForcesave: false,
    recentSection: true,
    favoritesSection: true,
    templatesSection: true,
    downloadTarGz: false,
    automaticallyCleanUp: {
      isAutoCleanUp: true,
      gap: 4,
    },
    canSearchByContent: true,
    defaultSharingAccessRights: [2],
    maxUploadThreadCount: 15,
    chunkUploadSize: 10485760,
    openEditorInSameTab: false,
  };
};

export const filesSettingsHandler = (): Response => {
  return new Response(JSON.stringify({ response: getFilesSettings() }));
};
