// (c) Copyright Ascensio System SIA 2009-2025
//
// This program is a free software product.
// You can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
// Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
// to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
// any third-party rights.
//
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
// the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
//
// You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
//
// The  interactive user interfaces in modified source and object code versions of the Program must
// display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
//
// Pursuant to Section 7(b) of the License you must retain the original Product logo when
// distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
// trademark law for use of our trademarks.
//
// All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
// content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
// International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode

import { BASE_URL, API_PREFIX } from "../../utils";

export const PATH_RECENT = /.*\/api\/2\.0\/files\/\d+\?.*/;

const recentEmptySuccess = {
  response: {
    files: [],
    folders: [],
    current: {
      parentId: 0,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      pinned: false,
      private: false,
      indexing: false,
      denyDownload: false,
      fileEntryType: 1,
      id: 28934,
      rootFolderId: 28934,
      canShare: false,
      security: {
        Read: true,
        Create: false,
        Delete: false,
        EditRoom: false,
        Rename: false,
        CopyTo: false,
        Copy: false,
        MoveTo: false,
        Move: false,
        Pin: false,
        Mute: false,
        EditAccess: false,
        Duplicate: false,
        Download: false,
        CopySharedLink: false,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: false,
        Embed: false,
        ChangeOwner: false,
        IndexExport: false,
        UseChat: false,
        FillForms: false,
        Edit: false,
        SubmitToFormGallery: false,
        Lock: false,
        CustomFilter: false,
        StartFilling: false,
        StopFilling: false,
        FillingStatus: false,
      },
      availableShareRights: {},
      title: "Recent",
      access: 0,
      shared: false,
      sharedForUser: false,
      parentShared: false,
      shortWebUrl: "",
      created: "2025-12-10T16:23:39.0000000+03:00",
      createdBy: {
        id: "0000000000-0000-000000-000000000",
        displayName: "Admin Admin",
        avatar:
          "/static/images/default_user_photo_size_82-82.png?hash=261361478",
        avatarOriginal:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMax:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMedium:
          "/static/images/default_user_photo_size_48-48.png?hash=261361478",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=261361478",
        profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
        hasAvatar: true,
        isAnonim: false,
      },
      updated: "2025-12-10T16:23:39.0000000+03:00",
      rootFolderType: 11,
      updatedBy: {
        id: "0000000000-0000-000000-000000000",
        displayName: "Admin Admin",
        avatar:
          "/static/images/default_user_photo_size_82-82.png?hash=261361478",
        avatarOriginal:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMax:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMedium:
          "/static/images/default_user_photo_size_48-48.png?hash=261361478",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=261361478",
        profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
        hasAvatar: true,
        isAnonim: false,
      },
      order: "",
    },
    pathParts: [
      {
        id: 28934,
        title: "Recent",
        folderType: 11,
      },
    ],
    startIndex: 0,
    count: 2,
    total: 2,
    new: 0,
  },
  count: 1,
  links: [
    {
      href: `${BASE_URL}/${API_PREFIX}/files/28934?count=100`,
      action: "GET",
    },
  ],
  status: 0,
  statusCode: 200,
};

const recentSuccess = {
  response: {
    files: [
      {
        folderId: 4,
        version: 1,
        versionGroup: 1,
        contentLength: "5.6 KB",
        pureContentLength: 5731,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=13&share=d28vZlZ5TzI2dUV4TjRWUW5kZ1p5SVEyNEtnT3BQdThKVW0yTFRDKzlzWT0_ImUxZTEzNWNkLWMwMTUtNGE0MS04MmFhLTNjNGVkNjU4MmM1MCI`,
        webUrl: `${BASE_URL}/doceditor?fileid=13&version=1&share=d28vZlZ5TzI2dUV4TjRWUW5kZ1p5SVEyNEtnT3BQdThKVW0yTFRDKzlzWT0_ImUxZTEzNWNkLWMwMTUtNGE0MS04MmFhLTNjNGVkNjU4MmM1MCI`,
        fileType: 5,
        fileExst: ".xlsx",
        comment: "Created",
        thumbnailStatus: 3,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: false,
          WebCustomFilterEditing: true,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:11:49.0000000+03:00",
        fileEntryType: 2,
        id: 13,
        rootFolderId: 4,
        originId: 10,
        originRoomId: 10,
        originTitle: "my",
        originRoomTitle: "my",
        canShare: false,
        security: {
          Read: true,
          Comment: false,
          FillForms: false,
          Review: false,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: false,
          Copy: true,
          Move: false,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: false,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: false,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Editing", "Comment", "Read", "Restrict"],
          ExternalLink: ["Editing", "Comment", "Read"],
          Group: ["ReadWrite", "Editing", "Comment", "Read", "Restrict"],
          PrimaryExternalLink: ["Editing", "Comment", "Read"],
        },
        requestToken:
          "d28vZlZ5TzI2dUV4TjRWUW5kZ1p5SVEyNEtnT3BQdThKVW0yTFRDKzlzWT0_ImUxZTEzNWNkLWMwMTUtNGE0MS04MmFhLTNjNGVkNjU4MmM1MCI",
        external: true,
        isLinkExpired: false,
        title: "Spreadsheet via link.xlsx",
        access: 2,
        sharedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        ownedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-11T13:11:24.0000000+03:00",
        createdBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-11T13:11:24.0000000+03:00",
        rootFolderType: 6,
        updatedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 14,
        version: 1,
        versionGroup: 1,
        contentLength: "7.54 KB",
        pureContentLength: 7726,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=12`,
        webUrl: `${BASE_URL}/doceditor?fileid=12&version=1`,
        fileType: 7,
        fileExst: ".docx",
        comment: "Created",
        thumbnailStatus: 3,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: true,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:10:45.0000000+03:00",
        fileEntryType: 2,
        id: 12,
        rootFolderId: 2,
        originId: 14,
        originRoomId: 14,
        originTitle: "Room",
        originRoomTitle: "Room",
        canShare: false,
        security: {
          Read: true,
          Comment: false,
          FillForms: false,
          Review: false,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: false,
          Lock: false,
          EditHistory: false,
          Copy: true,
          Move: false,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: false,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: false,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          ExternalLink: ["Editing", "Review", "Comment", "Read"],
          PrimaryExternalLink: ["Editing", "Review", "Comment", "Read"],
        },
        title: "Room document.docx",
        access: 3,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-11T13:10:22.0000000+03:00",
        createdBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-11T13:10:22.0000000+03:00",
        rootFolderType: 14,
        updatedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 4,
        version: 1,
        versionGroup: 1,
        contentLength: "7.54 KB",
        pureContentLength: 7726,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=11`,
        webUrl: `${BASE_URL}/doceditor?fileid=11&version=1`,
        fileType: 7,
        fileExst: ".docx",
        comment: "Created",
        thumbnailStatus: 3,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: true,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:09:23.0000000+03:00",
        fileEntryType: 2,
        id: 11,
        rootFolderId: 4,
        originId: 10,
        originRoomId: 10,
        originTitle: "my",
        originRoomTitle: "Shared with me",
        canShare: false,
        security: {
          Read: true,
          Comment: false,
          FillForms: false,
          Review: false,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: false,
          Copy: true,
          Move: false,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: false,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: false,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: [
            "ReadWrite",
            "Editing",
            "Review",
            "Comment",
            "Read",
            "Restrict",
          ],
          ExternalLink: ["Editing", "Review", "Comment", "Read"],
          Group: [
            "ReadWrite",
            "Editing",
            "Review",
            "Comment",
            "Read",
            "Restrict",
          ],
          PrimaryExternalLink: ["Editing", "Review", "Comment", "Read"],
        },
        title: "Shared document.docx",
        access: 2,
        sharedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        ownedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-11T13:08:43.0000000+03:00",
        createdBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-11T13:08:43.0000000+03:00",
        rootFolderType: 6,
        updatedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 7,
        version: 1,
        versionGroup: 1,
        contentLength: "34.92 KB",
        pureContentLength: 35762,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=6`,
        webUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=6`,
        fileType: 1,
        fileExst: ".zip",
        comment: "Uploaded",
        thumbnailStatus: 0,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: false,
          WebEdit: false,
          WebReview: false,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: false,
          WebComment: false,
          CanConvert: false,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:09:40.0000000+03:00",
        fileEntryType: 2,
        id: 6,
        rootFolderId: 7,
        originId: 7,
        originRoomId: 7,
        originTitle: "My documents",
        originRoomTitle: "My documents",
        canShare: false,
        shareSettings: {
          ExternalLink: 6,
        },
        security: {
          Read: true,
          Comment: true,
          FillForms: false,
          Review: true,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: true,
          Copy: true,
          Move: true,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: true,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: true,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Read", "Restrict", "None"],
          ExternalLink: ["Read", "None"],
          Group: ["ReadWrite", "Read", "Restrict", "None"],
          PrimaryExternalLink: ["Read", "None"],
        },
        title: "ONLYOFFICE Archive Sample.zip",
        access: 0,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-09-21T04:19:14.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-11T13:07:14.0000000+03:00",
        rootFolderType: 5,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 7,
        version: 1,
        versionGroup: 1,
        contentLength: "47.34 KB",
        pureContentLength: 48473,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=5`,
        webUrl: `${BASE_URL}/media/view/5`,
        fileType: 4,
        fileExst: ".png",
        comment: "Uploaded",
        thumbnailUrl: `${BASE_URL}/filehandler.ashx?action=thumb&fileid=5&version=1&hash=815437051`,
        thumbnailStatus: 1,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: true,
          MediaView: false,
          WebView: false,
          WebEdit: false,
          WebReview: false,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: false,
          WebComment: false,
          CanConvert: false,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:06:29.0000000+03:00",
        fileEntryType: 2,
        dimensions: {
          height: 624,
          width: 597,
        },
        id: 5,
        rootFolderId: 7,
        originId: 7,
        originRoomId: 7,
        originTitle: "My documents",
        originRoomTitle: "My documents",
        canShare: false,
        shareSettings: {
          ExternalLink: 6,
        },
        security: {
          Read: true,
          Comment: true,
          FillForms: false,
          Review: true,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: true,
          Copy: true,
          Move: true,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: true,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: true,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Read", "Restrict", "None"],
          ExternalLink: ["Read", "None"],
          Group: ["ReadWrite", "Read", "Restrict", "None"],
          PrimaryExternalLink: ["Read", "None"],
        },
        title: "ONLYOFFICE Image Sample.png",
        access: 0,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-10T14:07:25.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-11T13:02:10.0000000+03:00",
        rootFolderType: 5,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 7,
        version: 1,
        versionGroup: 1,
        contentLength: "75.02 KB",
        pureContentLength: 76825,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=3`,
        webUrl: `${BASE_URL}/doceditor?fileid=3&version=1`,
        fileType: 5,
        fileExst: ".xlsx",
        comment: "Created",
        thumbnailStatus: 0,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: false,
          WebCustomFilterEditing: true,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:06:31.0000000+03:00",
        fileEntryType: 2,
        id: 3,
        rootFolderId: 7,
        originId: 7,
        originRoomId: 7,
        originTitle: "My documents",
        originRoomTitle: "My documents",
        canShare: false,
        shareSettings: {
          ExternalLink: 6,
        },
        security: {
          Read: true,
          Comment: true,
          FillForms: false,
          Review: true,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: true,
          Copy: true,
          Move: true,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: true,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: true,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Editing", "Comment", "Read", "Restrict", "None"],
          ExternalLink: ["Editing", "Comment", "Read", "None"],
          Group: [
            "ReadWrite",
            "Editing",
            "Comment",
            "Read",
            "Restrict",
            "None",
          ],
          PrimaryExternalLink: ["Editing", "Comment", "Read", "None"],
        },
        title: "ONLYOFFICE Spreadsheet Sample.xlsx",
        access: 0,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-10T16:23:41.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-10T16:23:41.0000000+03:00",
        rootFolderType: 5,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 7,
        version: 1,
        versionGroup: 1,
        contentLength: "85.31 KB",
        pureContentLength: 87354,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=4`,
        webUrl: `${BASE_URL}/doceditor?fileid=4&version=1`,
        fileType: 6,
        fileExst: ".pptx",
        comment: "Created",
        thumbnailStatus: 0,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: false,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:06:33.0000000+03:00",
        fileEntryType: 2,
        id: 4,
        rootFolderId: 7,
        originId: 7,
        originRoomId: 7,
        originTitle: "My documents",
        originRoomTitle: "My documents",
        canShare: false,
        shareSettings: {
          ExternalLink: 6,
        },
        security: {
          Read: true,
          Comment: true,
          FillForms: false,
          Review: true,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: true,
          Copy: true,
          Move: true,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: true,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: true,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Editing", "Comment", "Read", "Restrict", "None"],
          ExternalLink: ["Editing", "Comment", "Read", "None"],
          Group: [
            "ReadWrite",
            "Editing",
            "Comment",
            "Read",
            "Restrict",
            "None",
          ],
          PrimaryExternalLink: ["Editing", "Comment", "Read", "None"],
        },
        title: "ONLYOFFICE Presentation Sample.pptx",
        access: 0,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-10T16:23:41.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-10T16:23:41.0000000+03:00",
        rootFolderType: 5,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 7,
        version: 1,
        versionGroup: 1,
        contentLength: "1.27 MB",
        pureContentLength: 1329569,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=2`,
        webUrl: `${BASE_URL}/doceditor?fileid=2&version=1`,
        fileType: 10,
        fileExst: ".pdf",
        comment: "Created",
        thumbnailStatus: 0,
        locked: false,
        hasDraft: false,
        formFillingStatus: 0,
        isForm: true,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: false,
          WebEdit: true,
          WebReview: false,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: true,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:06:35.0000000+03:00",
        fileEntryType: 2,
        id: 2,
        rootFolderId: 7,
        originId: 7,
        originRoomId: 7,
        originTitle: "My documents",
        originRoomTitle: "My documents",
        canShare: false,
        shareSettings: {
          ExternalLink: 6,
        },
        security: {
          Read: true,
          Comment: true,
          FillForms: false,
          Review: true,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: true,
          Copy: true,
          Move: true,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: true,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: true,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Editing", "FillForms", "Restrict", "None"],
          ExternalLink: ["Editing", "FillForms", "None"],
          Group: ["ReadWrite", "Editing", "FillForms", "Restrict", "None"],
          PrimaryExternalLink: ["Editing", "FillForms", "None"],
        },
        title: "ONLYOFFICE Resume Sample.pdf",
        access: 0,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-10T16:23:40.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-10T16:23:40.0000000+03:00",
        rootFolderType: 5,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
      {
        folderId: 127647,
        version: 1,
        versionGroup: 1,
        contentLength: "400.77 KB",
        pureContentLength: 410390,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=1`,
        webUrl: `${BASE_URL}/doceditor?fileid=1&version=1`,
        fileType: 7,
        fileExst: ".docx",
        comment: "Created",
        thumbnailStatus: 0,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: true,
          WebCustomFilterEditing: false,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:06:39.0000000+03:00",
        fileEntryType: 2,
        id: 1,
        rootFolderId: 12764,
        originId: 12764,
        originRoomId: 12764,
        originTitle: "My documents",
        originRoomTitle: "My documents",
        canShare: false,
        shareSettings: {
          ExternalLink: 6,
        },
        security: {
          Read: true,
          Comment: true,
          FillForms: false,
          Review: true,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: true,
          Copy: true,
          Move: true,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: true,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: true,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: [
            "ReadWrite",
            "Editing",
            "Review",
            "Comment",
            "Read",
            "Restrict",
            "None",
          ],
          ExternalLink: ["Editing", "Review", "Comment", "Read", "None"],
          Group: [
            "ReadWrite",
            "Editing",
            "Review",
            "Comment",
            "Read",
            "Restrict",
            "None",
          ],
          PrimaryExternalLink: ["Editing", "Review", "Comment", "Read", "None"],
        },
        title: "ONLYOFFICE Document Sample.docx",
        access: 0,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-10T16:23:39.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-10T16:23:39.0000000+03:00",
        rootFolderType: 5,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=1168361071",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=1168361071",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=1168361071",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=1168361071",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
    ],
    folders: [],
    current: {
      parentId: 0,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      pinned: false,
      private: false,
      indexing: false,
      denyDownload: false,
      fileEntryType: 1,
      id: 28934,
      rootFolderId: 28934,
      canShare: false,
      security: {
        Read: true,
        Create: false,
        Delete: false,
        EditRoom: false,
        Rename: false,
        CopyTo: false,
        Copy: false,
        MoveTo: false,
        Move: false,
        Pin: false,
        Mute: false,
        EditAccess: false,
        Duplicate: false,
        Download: false,
        CopySharedLink: false,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: false,
        Embed: false,
        ChangeOwner: false,
        IndexExport: false,
        UseChat: false,
        FillForms: false,
        Edit: false,
        SubmitToFormGallery: false,
        Lock: false,
        CustomFilter: false,
        StartFilling: false,
        StopFilling: false,
        FillingStatus: false,
      },
      availableShareRights: {},
      title: "Recent",
      access: 0,
      shared: false,
      sharedForUser: false,
      parentShared: false,
      shortWebUrl: "",
      created: "2025-12-10T16:23:39.0000000+03:00",
      createdBy: {
        id: "0000000000-0000-000000-000000000",
        displayName: "Admin Admin",
        avatar:
          "/static/images/default_user_photo_size_82-82.png?hash=261361478",
        avatarOriginal:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMax:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMedium:
          "/static/images/default_user_photo_size_48-48.png?hash=261361478",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=261361478",
        profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
        hasAvatar: true,
        isAnonim: false,
      },
      updated: "2025-12-10T16:23:39.0000000+03:00",
      rootFolderType: 11,
      updatedBy: {
        id: "0000000000-0000-000000-000000000",
        displayName: "Admin Admin",
        avatar:
          "/static/images/default_user_photo_size_82-82.png?hash=261361478",
        avatarOriginal:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMax:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMedium:
          "/static/images/default_user_photo_size_48-48.png?hash=261361478",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=261361478",
        profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
        hasAvatar: true,
        isAnonim: false,
      },
      order: "",
    },
    pathParts: [
      {
        id: 28934,
        title: "Recent",
        folderType: 11,
      },
    ],
    startIndex: 0,
    count: 2,
    total: 2,
    new: 0,
  },
  count: 1,
  links: [
    {
      href: `${BASE_URL}/${API_PREFIX}/files/28934?count=100`,
      action: "GET",
    },
  ],
  status: 0,
  statusCode: 200,
};

const recentOneFileSuccess = {
  response: {
    files: [
      {
        folderId: 4,
        version: 1,
        versionGroup: 1,
        contentLength: "5.6 KB",
        pureContentLength: 5731,
        fileStatus: 32,
        mute: false,
        viewUrl: `${BASE_URL}/filehandler.ashx?action=download&fileid=13&share=d28vZlZ5TzI2dUV4TjRWUW5kZ1p5SVEyNEtnT3BQdThKVW0yTFRDKzlzWT0_ImUxZTEzNWNkLWMwMTUtNGE0MS04MmFhLTNjNGVkNjU4MmM1MCI`,
        webUrl: `${BASE_URL}/doceditor?fileid=13&version=1&share=d28vZlZ5TzI2dUV4TjRWUW5kZ1p5SVEyNEtnT3BQdThKVW0yTFRDKzlzWT0_ImUxZTEzNWNkLWMwMTUtNGE0MS04MmFhLTNjNGVkNjU4MmM1MCI`,
        fileType: 5,
        fileExst: ".xlsx",
        comment: "Created",
        thumbnailStatus: 3,
        locked: false,
        formFillingStatus: 0,
        viewAccessibility: {
          ImageView: false,
          MediaView: false,
          WebView: true,
          WebEdit: true,
          WebReview: false,
          WebCustomFilterEditing: true,
          WebRestrictedEditing: false,
          WebComment: true,
          CanConvert: true,
          MustConvert: false,
        },
        lastOpened: "2025-12-11T13:11:49.0000000+03:00",
        fileEntryType: 2,
        id: 13,
        rootFolderId: 4,
        originId: 10,
        originRoomId: 10,
        originTitle: "my",
        originRoomTitle: "my",
        canShare: false,
        security: {
          Read: true,
          Comment: false,
          FillForms: false,
          Review: false,
          Edit: false,
          Delete: false,
          CustomFilter: false,
          Rename: false,
          ReadHistory: true,
          Lock: false,
          EditHistory: false,
          Copy: true,
          Move: false,
          Duplicate: false,
          SubmitToFormGallery: false,
          Download: true,
          Convert: false,
          CreateRoomFrom: false,
          CopyLink: false,
          Embed: false,
          StartFilling: false,
          FillingStatus: false,
          ResetFilling: false,
          StopFilling: false,
          OpenForm: false,
          Vectorization: false,
          AskAi: false,
          CopySharedLink: false,
        },
        availableShareRights: {
          User: ["ReadWrite", "Editing", "Comment", "Read", "Restrict"],
          ExternalLink: ["Editing", "Comment", "Read"],
          Group: ["ReadWrite", "Editing", "Comment", "Read", "Restrict"],
          PrimaryExternalLink: ["Editing", "Comment", "Read"],
        },
        requestToken:
          "d28vZlZ5TzI2dUV4TjRWUW5kZ1p5SVEyNEtnT3BQdThKVW0yTFRDKzlzWT0_ImUxZTEzNWNkLWMwMTUtNGE0MS04MmFhLTNjNGVkNjU4MmM1MCI",
        external: true,
        isLinkExpired: false,
        title: "Spreadsheet via link.xlsx",
        access: 2,
        sharedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        ownedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-11T13:11:24.0000000+03:00",
        createdBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        updated: "2025-12-11T13:11:24.0000000+03:00",
        rootFolderType: 6,
        updatedBy: {
          id: "d23f91ff-1068-4408-92e6-3d862972e3b1",
          displayName: "room admin",
          avatar:
            "/static/images/default_user_photo_size_82-82.png?hash=985105309",
          avatarOriginal:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMax:
            "/static/images/default_user_photo_size_200-200.png?hash=985105309",
          avatarMedium:
            "/static/images/default_user_photo_size_48-48.png?hash=985105309",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=985105309",
          profileUrl: `${BASE_URL}/accounts/people/filter?search=roomadmin%40test.com`,
          hasAvatar: false,
          isAnonim: false,
        },
        order: "",
      },
    ],
    folders: [],
    current: {
      parentId: 0,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      pinned: false,
      private: false,
      indexing: false,
      denyDownload: false,
      fileEntryType: 1,
      id: 28934,
      rootFolderId: 28934,
      canShare: false,
      security: {
        Read: true,
        Create: false,
        Delete: false,
        EditRoom: false,
        Rename: false,
        CopyTo: false,
        Copy: false,
        MoveTo: false,
        Move: false,
        Pin: false,
        Mute: false,
        EditAccess: false,
        Duplicate: false,
        Download: false,
        CopySharedLink: false,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: false,
        Embed: false,
        ChangeOwner: false,
        IndexExport: false,
        UseChat: false,
        FillForms: false,
        Edit: false,
        SubmitToFormGallery: false,
        Lock: false,
        CustomFilter: false,
        StartFilling: false,
        StopFilling: false,
        FillingStatus: false,
      },
      availableShareRights: {},
      title: "Recent",
      access: 0,
      shared: false,
      sharedForUser: false,
      parentShared: false,
      shortWebUrl: "",
      created: "2025-12-10T16:23:39.0000000+03:00",
      createdBy: {
        id: "0000000000-0000-000000-000000000",
        displayName: "Admin Admin",
        avatar:
          "/static/images/default_user_photo_size_82-82.png?hash=261361478",
        avatarOriginal:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMax:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMedium:
          "/static/images/default_user_photo_size_48-48.png?hash=261361478",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=261361478",
        profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
        hasAvatar: true,
        isAnonim: false,
      },
      updated: "2025-12-10T16:23:39.0000000+03:00",
      rootFolderType: 11,
      updatedBy: {
        id: "0000000000-0000-000000-000000000",
        displayName: "Admin Admin",
        avatar:
          "/static/images/default_user_photo_size_82-82.png?hash=261361478",
        avatarOriginal:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMax:
          "/static/images/default_user_photo_size_200-200.png?hash=261361478",
        avatarMedium:
          "/static/images/default_user_photo_size_48-48.png?hash=261361478",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=261361478",
        profileUrl: `${BASE_URL}/accounts/people/filter?search=admin%40gmail.com`,
        hasAvatar: true,
        isAnonim: false,
      },
      order: "",
    },
    pathParts: [
      {
        id: 28934,
        title: "Recent",
        folderType: 11,
      },
    ],
    startIndex: 0,
    count: 2,
    total: 2,
    new: 0,
  },
  count: 1,
  links: [
    {
      href: `${BASE_URL}/${API_PREFIX}/files/28934?count=100`,
      action: "GET",
    },
  ],
  status: 0,
  statusCode: 200,
};

export const recentEmptyHandler = () => {
  return new Response(JSON.stringify(recentEmptySuccess));
};

export const recentHandler = () => {
  return new Response(JSON.stringify(recentSuccess));
};

export const recentOneFileHandler = () => {
  return new Response(JSON.stringify(recentOneFileSuccess));
};
