// (c) Copyright Ascensio System SIA 2009-2024
//
// This program is a free software product.
// You can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
// Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
// to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
// any third-party rights.
//
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
// the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
//
// You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
//
// The  interactive user interfaces in modified source and object code versions of the Program must
// display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
//
// Pursuant to Section 7(b) of the License you must retain the original Product logo when
// distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
// trademark law for use of our trademarks.
//
// All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
// content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
// International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode

import { TGetRooms, TRoom } from "../../../../api/rooms/types";
import { HEADER_FILTERED_ROOMS_LIST, HEADER_ROOMS_LIST } from "../../utils";

export const PATH_ROOMS_LIST = "files/rooms?*";

const current = {
  parentId: 0,
  filesCount: 0,
  foldersCount: 0,
  new: 0,
  mute: false,
  pinned: false,
  private: false,
  indexing: false,
  denyDownload: false,
  fileEntryType: 1,
  id: 100,
  rootFolderId: 100,
  canShare: false,
  security: {
    Read: true,
    Create: true,
    Delete: false,
    EditRoom: false,
    Rename: false,
    CopyTo: false,
    Copy: false,
    MoveTo: true,
    Move: false,
    Pin: false,
    Mute: false,
    EditAccess: false,
    Duplicate: false,
    Download: false,
    CopySharedLink: false,
    Reconnect: false,
    CreateRoomFrom: false,
    CopyLink: false,
    Embed: false,
    ChangeOwner: false,
    IndexExport: false,
  },
  title: "Trash",
  access: 0,
  shared: false,
  created: new Date().toString(),
  createdBy: {
    id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
    displayName: "Administrator ",
    avatar: "/static/images/default_user_photo_size_82-82.png?hash=520061207",
    avatarOriginal:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMax:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMedium:
      "/static/images/default_user_photo_size_48-48.png?hash=520061207",
    avatarSmall:
      "/static/images/default_user_photo_size_32-32.png?hash=520061207",
    profileUrl: "",
    hasAvatar: false,
    isAnonim: false,
  },
  updated: new Date().toString(),
  rootFolderType: 100,
  parentRoomType: 100,
  updatedBy: {
    id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
    displayName: "Administrator ",
    avatar: "/static/images/default_user_photo_size_82-82.png?hash=520061207",
    avatarOriginal:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMax:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMedium:
      "/static/images/default_user_photo_size_48-48.png?hash=520061207",
    avatarSmall:
      "/static/images/default_user_photo_size_32-32.png?hash=520061207",
    profileUrl: "",
    hasAvatar: false,
    isAnonim: false,
  },
};

export const getRoomList = (filtered: boolean = false) => {
  const folders: TRoom[] = [
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 2,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 40,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        Reconnect: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 41,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 42,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 43,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 44,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "New room",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 45,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "New room",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 46,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 39,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "s",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF6680",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 24,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "2 (2) (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF6680",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 25,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "2 (2) (2)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF8F40",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 31,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "3 (1) (1) (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF8F40",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 22,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "3 (3)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF8F40",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 29,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "3 (3) (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: ["sdfs"],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "F2D230",
      },
      pinned: false,
      roomType: 2,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 6942,
      fileEntryType: 1,
      id: 8,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "fdsf",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: ["sdfs"],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "F2D230",
      },
      pinned: false,
      roomType: 2,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 6942,
      fileEntryType: 1,
      id: 20,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "fdsf (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 7,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "kk",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 18,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "kk (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 27,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "kk (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 30,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "kk (1) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 34,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
      },
      title: "kk (1) (1) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
  ];

  const filteredFolder = folders.filter((f, i) => i > 20);

  return {
    files: [],
    folders: filtered ? filteredFolder : folders,
    current,
    pathParts: [
      {
        id: 2,
        title: "Rooms",
      },
    ],
    startIndex: 0,
    total: 0,
    count: 0,
    new: 0,
  };
};

export const getEmptyRoomList = (): TGetRooms => {
  return {
    files: [],
    folders: [],
    current,
    pathParts: [
      {
        id: 100,
        title: "Trash",
      },
    ],
    startIndex: 0,
    total: 0,
    count: 0,
    new: 0,
  };
};

export const roomListHandler = (headers?: Headers): Response => {
  if (headers?.get(HEADER_FILTERED_ROOMS_LIST)) {
    return new Response(JSON.stringify({ response: getRoomList(true) }));
  }

  if (headers?.get(HEADER_ROOMS_LIST)) {
    return new Response(JSON.stringify({ response: getRoomList() }));
  }

  return new Response(JSON.stringify({ response: getEmptyRoomList() }));
};
