// (c) Copyright Ascensio System SIA 2009-2024
//
// This program is a free software product.
// You can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
// Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
// to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
// any third-party rights.
//
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
// the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
//
// You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
//
// The  interactive user interfaces in modified source and object code versions of the Program must
// display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
//
// Pursuant to Section 7(b) of the License you must retain the original Product logo when
// distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
// trademark law for use of our trademarks.
//
// All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
// content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
// International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode

import { TGetRooms, TRoom } from "../../../../api/rooms/types";
import { ShareAccessRights } from "../../../../enums";
import {
  CONTEXT_MENU_ROOMS_LIST,
  HEADER_FILTERED_ROOMS_LIST,
  HEADER_ROOMS_LIST,
} from "../../utils";

export const PATH_ROOMS_LIST = "files/rooms?*";

const current = {
  parentId: 0,
  filesCount: 0,
  foldersCount: 0,
  new: 0,
  mute: false,
  pinned: false,
  private: false,
  indexing: false,
  denyDownload: false,
  fileEntryType: 1,
  id: 2,
  rootFolderId: 2,
  canShare: false,
  security: {
    Read: true,
    Create: true,
    Delete: false,
    EditRoom: false,
    Rename: false,
    CopyTo: false,
    Copy: false,
    MoveTo: true,
    Move: false,
    Pin: false,
    Mute: false,
    EditAccess: false,
    Duplicate: false,
    Download: false,
    CopySharedLink: false,
    Reconnect: false,
    CreateRoomFrom: false,
    CopyLink: false,
    Embed: false,
    ChangeOwner: false,
    IndexExport: false,
  },
  title: "Rooms",
  access: 0,
  shared: false,
  created: new Date().toString(),
  createdBy: {
    id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
    displayName: "Administrator ",
    avatar: "/static/images/default_user_photo_size_82-82.png?hash=520061207",
    avatarOriginal:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMax:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMedium:
      "/static/images/default_user_photo_size_48-48.png?hash=520061207",
    avatarSmall:
      "/static/images/default_user_photo_size_32-32.png?hash=520061207",
    profileUrl: "",
    hasAvatar: false,
    isAnonim: false,
  },
  updated: new Date().toString(),
  rootFolderType: 14,
  parentRoomType: 14,
  updatedBy: {
    id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
    displayName: "Administrator ",
    avatar: "/static/images/default_user_photo_size_82-82.png?hash=520061207",
    avatarOriginal:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMax:
      "/static/images/default_user_photo_size_200-200.png?hash=520061207",
    avatarMedium:
      "/static/images/default_user_photo_size_48-48.png?hash=520061207",
    avatarSmall:
      "/static/images/default_user_photo_size_32-32.png?hash=520061207",
    profileUrl: "",
    hasAvatar: false,
    isAnonim: false,
  },
};

const getRoomList = (filtered: boolean = false) => {
  const folders: TRoom[] = [
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 33,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        Reconnect: false,
        UseChat: false,
      },
      title:
        "Very loooong looooong looooong looooong loooooong loooooong loooong room name Very loooong looooong looooong looooong loooooong loooooong loooong room name Very loooong looooong looooong looooong loooooong loooooong loooong room name Very loooong looooong looooong looooong loooooong loooooong loooong room name Very loooong looooong looooong looooong loooooong loooooong loooong room name Very loooong looooong looooong looooong loooooong loooooong loooong room name Very loooong looooong looooong looooong loooooong loooooong loooong room name",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 2,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 40,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        Reconnect: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 41,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 42,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 43,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 44,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 45,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 46,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "New room",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 39,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "s",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF6680",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 24,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "2 (2) (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF6680",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 25,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "2 (2) (2)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF8F40",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 31,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "3 (1) (1) (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF8F40",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 22,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "3 (3)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 0,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "FF8F40",
      },
      pinned: false,
      roomType: 5,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 0,
      fileEntryType: 1,
      id: 29,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "3 (3) (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: ["sdfs"],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "F2D230",
      },
      pinned: false,
      roomType: 2,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 6942,
      fileEntryType: 1,
      id: 8,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "fdsf",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: ["sdfs"],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "F2D230",
      },
      pinned: false,
      roomType: 2,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 6942,
      fileEntryType: 1,
      id: 20,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: false,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "fdsf (1)",
      access: 0,
      shared: false,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 7,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 18,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 27,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 30,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 34,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 36,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (1) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 38,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (1) (1) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 32,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (2)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 35,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (2) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
    {
      parentId: 2,
      filesCount: 1,
      foldersCount: 0,
      new: 0,
      mute: false,
      tags: [],
      logo: {
        original: "",
        large: "",
        medium: "",
        small: "",
        color: "61C059",
      },
      pinned: false,
      roomType: 6,
      private: false,
      indexing: false,
      denyDownload: false,
      inRoom: true,
      usedSpace: 2154431,
      fileEntryType: 1,
      id: 37,
      rootFolderId: 2,
      canShare: true,
      security: {
        Read: true,
        Create: true,
        Delete: false,
        EditRoom: true,
        Rename: true,
        CopyTo: true,
        Copy: true,
        MoveTo: true,
        Move: true,
        Pin: true,
        Mute: true,
        EditAccess: true,
        Duplicate: true,
        Download: true,
        CopySharedLink: true,
        Reconnect: false,
        CreateRoomFrom: false,
        CopyLink: true,
        Embed: true,
        ChangeOwner: true,
        IndexExport: false,
        UseChat: false,
      },
      title: "kk (1) (1) (2) (1) (1)",
      access: 0,
      shared: true,
      created: new Date().toString(),
      createdBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
      updated: new Date().toString(),
      rootFolderType: 14,
      updatedBy: {
        id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
        displayName: "Administrator ",
        avatarSmall:
          "/static/images/default_user_photo_size_32-32.png?hash=520061207",
        profileUrl: "",
        hasAvatar: false,
      },
    },
  ];

  const filteredFolder = folders.filter((f, i) => i > 20);

  return {
    files: [],
    folders: filtered ? filteredFolder : folders,
    current,
    pathParts: [
      {
        id: 2,
        title: "Rooms",
      },
    ],
    startIndex: 0,
    total: 0,
    count: 0,
    new: 0,
  };
};

const getEmptyRoomList = (): TGetRooms => {
  return {
    files: [],
    folders: [],
    current,
    pathParts: [
      {
        id: 2,
        title: "Rooms",
      },
    ],
    startIndex: 0,
    total: 0,
    count: 0,
    new: 0,
  };
};

const getRoomSecurity = (
  userAccess: ShareAccessRights,
  isDocAdmin: boolean,
) => {
  if (isDocAdmin) {
    switch (userAccess) {
      case ShareAccessRights.RoomManager:
        return {
          ChangeOwner: true,
          Copy: true,
          CopyLink: true,
          CopySharedLink: true,
          CopyTo: true,
          Create: true,
          CreateRoomFrom: false,
          Delete: false,
          Download: true,
          Duplicate: true,
          EditAccess: true,
          EditRoom: true,
          Embed: true,
          IndexExport: true,
          Move: true,
          MoveTo: true,
          Mute: true,
          Pin: true,
          Read: true,
          Reconnect: false,
          Rename: true,
          UseChat: false,
        };
      case ShareAccessRights.Collaborator:
        return {
          ChangeOwner: true,
          Copy: true,
          CopyLink: true,
          CopySharedLink: true,
          CopyTo: true,
          Create: true,
          CreateRoomFrom: false,
          Delete: false,
          Download: true,
          Duplicate: true,
          EditAccess: false,
          EditRoom: false,
          Embed: false,
          IndexExport: false,
          Move: true,
          MoveTo: true,
          Mute: true,
          Pin: true,
          Read: true,
          Reconnect: false,
          Rename: false,
          UseChat: false,
        };
      case ShareAccessRights.None:
        return {
          ChangeOwner: true,
          Copy: true,
          CopyLink: true,
          CopySharedLink: true,
          CopyTo: true,
          Create: true,
          CreateRoomFrom: false,
          Delete: false,
          Download: true,
          Duplicate: true,
          EditAccess: false,
          EditRoom: false,
          Embed: false,
          IndexExport: true,
          Move: true,
          MoveTo: true,
          Mute: true,
          Pin: true,
          Read: true,
          Reconnect: false,
          Rename: false,
          UseChat: false,
        };
      default:
        return {};
    }
  } else {
    switch (userAccess) {
      case ShareAccessRights.RoomManager:
        return {
          ChangeOwner: false,
          Copy: true,
          CopyLink: true,
          CopySharedLink: true,
          CopyTo: true,
          Create: true,
          CreateRoomFrom: false,
          Delete: false,
          Download: true,
          Duplicate: true,
          EditAccess: true,
          EditRoom: true,
          Embed: true,
          IndexExport: true,
          Move: false,
          MoveTo: true,
          Mute: true,
          Pin: true,
          Read: true,
          Reconnect: false,
          Rename: true,
          UseChat: false,
        };
      case ShareAccessRights.Collaborator:
        return {
          ChangeOwner: false,
          Copy: true,
          CopyLink: true,
          CopySharedLink: true,
          CopyTo: true,
          Create: true,
          CreateRoomFrom: false,
          Delete: false,
          Download: true,
          Duplicate: false,
          EditAccess: false,
          EditRoom: false,
          Embed: false,
          IndexExport: false,
          Move: false,
          MoveTo: true,
          Mute: true,
          Pin: true,
          Read: true,
          Reconnect: false,
          Rename: false,
          UseChat: false,
        };
      case ShareAccessRights.None:
        return {
          ChangeOwner: true,
          Copy: true,
          CopyLink: true,
          CopySharedLink: true,
          CopyTo: true,
          Create: true,
          CreateRoomFrom: false,
          Delete: true,
          Download: true,
          Duplicate: true,
          EditAccess: true,
          EditRoom: true,
          Embed: true,
          IndexExport: true,
          Move: true,
          MoveTo: true,
          Mute: true,
          Pin: true,
          Read: true,
          Reconnect: true,
          Rename: true,
          UseChat: false,
        };
      default:
        return {};
    }
  }
};

const getContextMenuRoomList = ({
  access = ShareAccessRights.None,
  inRoom = true,
  isDocAdmin = true,
}: {
  access?: ShareAccessRights;
  inRoom?: boolean;
  isDocAdmin?: boolean;
}) => {
  const security = getRoomSecurity(access, isDocAdmin);

  return {
    files: [],
    folders: [
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 5,
        private: false,
        indexing: false,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: 10,
        rootFolderId: 2,
        canShare: true,
        security: { ...security, Embed: false },
        title: "Custom without share",
        access,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-09T11:42:52.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-12-09T11:42:52.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
      },
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 6,
        private: false,
        indexing: false,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: 11,
        rootFolderId: 2,
        canShare: true,
        security,
        title: "Public",
        access,
        shared: true,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-09T11:42:52.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-12-09T11:42:52.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
      },
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 1,
        private: false,
        indexing: false,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: 12,
        rootFolderId: 2,
        canShare: true,
        security,
        title: "Form room",
        access,
        shared: true,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-09T11:42:52.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-12-09T11:42:52.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
      },
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 5,
        private: false,
        indexing: false,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: 13,
        rootFolderId: 2,
        canShare: true,
        security,
        title: "Custom",
        access,
        shared: true,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-09T11:42:52.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-12-09T11:42:52.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
      },
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 6,
        private: false,
        indexing: false,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: "box-821",
        rootFolderId: 2,
        canShare: true,
        security: { ...security, Duplicate: false },
        title: "Public third-party",
        access,
        shared: true,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-09-03T15:22:08.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-09-03T15:22:26.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        providerItem: true,
        providerKey: "Box",
        providerId: 821,
      },
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 2,
        private: false,
        indexing: false,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: 14,
        rootFolderId: 2,
        canShare: false,
        security: { ...security, Embed: false, CopySharedLink: false },
        title: "Collaboration",
        access,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-09T11:42:52.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-12-09T11:42:52.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
      },
      {
        parentId: 2,
        filesCount: 0,
        foldersCount: 0,
        new: 0,
        mute: false,
        tags: [],
        logo: {
          original: "",
          large: "",
          medium: "",
          small: "",
          color: "FF7FD4",
        },
        pinned: false,
        roomType: 8,
        private: false,
        indexing: true,
        denyDownload: false,
        inRoom,
        fileEntryType: 1,
        id: 15,
        rootFolderId: 2,
        canShare: false,
        security: {
          ...security,
          Embed: false,
          CopySharedLink: false,
        },
        title: "VDR",
        access,
        shared: false,
        sharedForUser: false,
        parentShared: false,
        shortWebUrl: "",
        created: "2025-12-09T11:42:52.0000000+03:00",
        createdBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
        updated: "2025-12-09T11:42:52.0000000+03:00",
        rootFolderType: 14,
        parentRoomType: 14,
        updatedBy: {
          id: "66faa6e4-f133-11ea-b126-00ffeec8b4ef",
          displayName: "Administrator ",
          avatarSmall:
            "/static/images/default_user_photo_size_32-32.png?hash=520061207",
          profileUrl: "",
          hasAvatar: false,
        },
      },
    ],
    current,
    pathParts: [
      {
        id: 2,
        title: "Rooms",
      },
    ],
    startIndex: 0,
    total: 7,
    count: 7,
    new: 0,
  };
};

export const roomListHandler = (
  headers?: Headers,
  params?: {
    access?: ShareAccessRights;
    inRoom?: boolean;
    isDocAdmin?: boolean;
  },
): Response => {
  if (headers?.get(HEADER_FILTERED_ROOMS_LIST)) {
    return new Response(JSON.stringify({ response: getRoomList(true) }));
  }

  if (headers?.get(HEADER_ROOMS_LIST)) {
    return new Response(JSON.stringify({ response: getRoomList() }));
  }

  if (headers?.get(CONTEXT_MENU_ROOMS_LIST)) {
    return new Response(
      JSON.stringify({ response: getContextMenuRoomList(params ?? {}) }),
    );
  }

  return new Response(JSON.stringify({ response: getEmptyRoomList() }));
};
