/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

const fs = require("fs");
const path = require("path");

const { BASE_DIR, getWorkSpaces, getAllFiles } = require("./files");

// Directories pruned while walking the tree (matched as a path substring,
// same convention as getAllFiles). Keep in sync with the source-code scans
// used by the other tests in this package.
const EXCLUDE_DIRS = [
  ".nx",
  ".yarn",
  ".github",
  ".vscode",
  ".git",
  ".next",
  "node_modules",
  "dist",
  "coverage",
  "storybook-static",
  "__mocks__",
  "__tests__",
  "e2e",
  "campaigns",
  ".meta",
];

const SOURCE_EXT_REGEX = /\.(jsx?|tsx?)$/;

// The canonical marker every first-party source file must carry at the top.
const LICENSE_MARKER = "SPDX-License-Identifier: AGPL-3.0-only";

// How far into the file we look for the header (it must be at the top, not
// buried somewhere in the body).
const HEADER_LOOKUP_CHARS = 2048;

// Files that are not hand-authored first-party source and therefore are not
// expected to carry the header.
const isExcludedFile = (repoRelPath) => {
  return (
    !SOURCE_EXT_REGEX.test(repoRelPath) ||
    /\.(test|spec|stories)\./.test(repoRelPath) ||
    /\.d\.ts$/.test(repoRelPath) ||
    /\.config\.(jsx?|tsx?)$/.test(repoRelPath) ||
    /(^|\/)(playwright|vitest|next|vite|jest|babel)\.config\./.test(
      repoRelPath,
    ) ||
    /mockData/.test(repoRelPath) ||
    /autoGenerated/.test(repoRelPath) ||
    /(^|\/)public\/scripts\//.test(repoRelPath)
  );
};

const hasLicenseHeader = (fileText) => {
  return fileText.slice(0, HEADER_LOOKUP_CHARS).includes(LICENSE_MARKER);
};

// The single source of truth for the header wording lives in the VS Code
// `licenser` config of frontend.code-workspace. We read it from there so the
// test can never drift from what the editor auto-inserts.
const WORKSPACE_PATH = path.resolve(BASE_DIR, "frontend.code-workspace");

let canonicalHeaderCache = null;

const getCanonicalHeader = () => {
  if (canonicalHeaderCache) return canonicalHeaderCache;

  const raw = fs.readFileSync(WORKSPACE_PATH, "utf8");

  const authorMatch = raw.match(/"licenser\.author"\s*:\s*"((?:[^"\\]|\\.)*)"/);
  const headerMatch = raw.match(
    /"licenser\.customHeader"\s*:\s*"((?:[^"\\]|\\.)*)"/,
  );
  if (!authorMatch || !headerMatch) {
    throw new Error(
      "Could not read licenser.author / licenser.customHeader from " +
        "frontend.code-workspace",
    );
  }

  // The captured groups are JSON-escaped string bodies; decode them. The
  // workspace stores line breaks double-escaped ("\\n"), so a single JSON
  // decode leaves literal "\n" sequences that we turn into real newlines
  // (that is exactly how the licenser extension expands the template).
  const author = JSON.parse(`"${authorMatch[1]}"`);
  const template = JSON.parse(`"${headerMatch[1]}"`).replace(/\\r\\n|\\n/g, "\n");

  // The editor inserts the author verbatim; the year is maintained by the
  // "Update copyright year" task, so we keep @YEAR@ as a placeholder here and
  // match it against any 4-digit year at compare time.
  const expectedBody = template.replace(/@AUTHOR@/g, author);

  canonicalHeaderCache = { author, template, expectedBody };
  return canonicalHeaderCache;
};

// Pulls the body of the leading /* ... */ block comment out of a file and
// strips the comment framing, so it can be compared to the canonical wording.
// Only a block comment at the very top of the file counts (an optional BOM /
// leading whitespace aside); anything else means there is no canonical header.
const extractHeaderText = (fileText) => {
  const match = fileText.match(/^﻿?\s*\/\*([\s\S]*?)\*\//);
  if (!match) return null;

  const lines = match[1]
    .split(/\r?\n/)
    .map((line) => line.replace(/^\s*\*\s?/, "").replace(/\s+$/, ""));

  while (lines.length && lines[0] === "") lines.shift();
  while (lines.length && lines[lines.length - 1] === "") lines.pop();

  return lines.join("\n");
};

const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// True when the file's leading comment matches the canonical header word for
// word (any 4-digit copyright year is accepted).
const headerContentMatches = (fileText) => {
  const actual = extractHeaderText(fileText);
  if (actual === null) return false;

  const { expectedBody } = getCanonicalHeader();
  const pattern = `^${escapeRegExp(expectedBody).replace(/@YEAR@/g, "\\d{4}")}$`;

  return new RegExp(pattern).test(actual);
};

const toRepoRelative = (absPath) => {
  return path.relative(BASE_DIR, absPath).split(path.sep).join("/");
};

// Returns the repo-relative POSIX paths of every first-party source file that
// is in scope for the license-header check, sorted for stable output.
const getSourceFiles = () => {
  const workspaces = getWorkSpaces({ excludeUiKit: true });

  const files = workspaces.flatMap((wsPath) =>
    getAllFiles(wsPath, EXCLUDE_DIRS).filter(Boolean),
  );

  return files
    .map(toRepoRelative)
    .filter((relPath) => !isExcludedFile(relPath))
    .sort();
};

// Classifies every in-scope file:
//  - `missing`  : no AGPL header at all;
//  - `mismatch` : has a header, but the wording differs from the canonical one.
const scanLicenseHeaders = () => {
  const missing = [];
  const mismatch = [];

  for (const relPath of getSourceFiles()) {
    const absPath = path.resolve(BASE_DIR, relPath);
    const fileText = fs.readFileSync(absPath, "utf8");
    if (!hasLicenseHeader(fileText)) {
      missing.push(relPath);
    } else if (!headerContentMatches(fileText)) {
      mismatch.push(relPath);
    }
  }

  return { missing, mismatch };
};

module.exports = {
  BASE_DIR,
  EXCLUDE_DIRS,
  LICENSE_MARKER,
  SOURCE_EXT_REGEX,
  isExcludedFile,
  hasLicenseHeader,
  getCanonicalHeader,
  extractHeaderText,
  headerContentMatches,
  toRepoRelative,
  getSourceFiles,
  scanLicenseHeaders,
};
