/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Toast } from "@docspace/ui-kit/components/toast";
import type { TUser } from "@docspace/shared/api/people/types";
import type {
  TGetColorTheme,
  TSettings,
} from "@docspace/shared/api/settings/types";
import type { ThemeKeys } from "@docspace/shared/enums";
import { TranslationProvider } from "@docspace/ui-kit/providers/translation";
import type {
  TTranslations,
  TTranslationProvider,
} from "@docspace/ui-kit/providers/translation";
import { ThemeProvider } from "@docspace/ui-kit/providers/theme";
import type { TThemeProvider } from "@docspace/ui-kit/providers/theme";
import { ApiProvider } from "@docspace/ui-kit/providers/api";
import { getCookie } from "@docspace/ui-kit/utils/cookie";
import { combineUrl } from "@docspace/shared/utils/combineUrl";

import { translations } from "@/utils/autoGeneratedTranslations";

import ErrorProvider from "./ErrorProvider";

export type TContextData = {
  user: TUser | undefined;
  settings: TSettings | undefined;
  initialTheme: ThemeKeys | undefined;
  systemTheme: ThemeKeys | undefined;
  colorTheme: TGetColorTheme | undefined;
  locale?: string;
};

export type TProviders = {
  children: React.ReactNode;
  contextData: TContextData;
};

const getApiUrl = () => {
  if (typeof window === "undefined") {
    return "";
  }
  const origin = window.ClientConfig?.api?.origin || window.location.origin;
  const proxy = window.ClientConfig?.proxy?.url || "";

  return combineUrl(origin, proxy);
};

const Providers = ({ children, contextData }: TProviders) => {
  const { user, settings, initialTheme, systemTheme, colorTheme, locale } =
    contextData;

  const apiUrl = getApiUrl();
  const apiKey = getCookie("asc_auth_key") || "";

  return (
    <ApiProvider url={apiUrl} apiKey={apiKey} initSocket={false}>
      <TranslationProvider
        settings={settings as TTranslationProvider["settings"]}
        user={user as TTranslationProvider["user"]}
        locale={locale}
        translations={translations as TTranslations}
      >
        <ThemeProvider
          initialTheme={initialTheme}
          systemTheme={systemTheme}
          colorTheme={colorTheme as TThemeProvider["colorTheme"]}
          locale={locale}
        >
          <ErrorProvider {...contextData}>
            {children}
            <Toast isSSR />
          </ErrorProvider>
        </ThemeProvider>
      </TranslationProvider>
    </ApiProvider>
  );
};

export default Providers;
