import { translations } from "../../../autoGeneratedTranslations";
import path from "path";
import fs from "fs";
import {
  getSettings,
  getBuildVersion,
  getAuthProviders,
  getCapabilities,
  getAppearanceTheme,
  getLogoUrls,
  getCurrentSsoSettings,
} from "@docspace/common/api/settings";
import { getUser } from "@docspace/common/api/people";
import { checkIsAuthenticated } from "@docspace/common/api/user";
import { getClient, getScopeList } from "@docspace/common/api/oauth";
import { TenantStatus } from "@docspace/common/constants";
import { IScope } from "@docspace/common/utils/oauth/interfaces";
import winston, { stream } from "./logger";

export const getAssets = (): assetsType => {
  const manifest = fs.readFileSync(
    path.join(__dirname, "client/manifest.json"),
    "utf-8"
  );

  const assets = JSON.parse(manifest);

  return assets;
};

export const getScripts = (assets: assetsType): string[] | void => {
  if (!assets || typeof assets !== "object") return;
  const regTest = /static\/js\/.*/;
  const keys = [];

  for (let key in assets) {
    if (assets.hasOwnProperty(key) && regTest.test(key)) {
      keys.push(key);
    }
  }

  return keys;
};

export const loadPath = (language: string, nameSpace: string): string => {
  const path = translations?.get(language)?.get(nameSpace);

  return path;
};

export const getInitialState = async (
  query: MatchType
): Promise<IInitialState> => {
  let portalSettings: IPortalSettings,
    buildInfo: IBuildInfo,
    providers: ProvidersType,
    capabilities: ICapabilities,
    availableThemes: IThemes,
    logoUrls: ILogoUrl[],
    ssoSettings: ISSOSettings;

  const baseSettings = [
    getSettings(),
    getBuildVersion(),
    getAppearanceTheme(),
    getLogoUrls(),
  ];

  const settings = [
    getAuthProviders(),
    getCapabilities(),
    // getCurrentSsoSettings(),
  ];

  [portalSettings, buildInfo, availableThemes, logoUrls] = await Promise.all(
    baseSettings
  );

  if (portalSettings.tenantStatus !== TenantStatus.PortalRestore)
    [providers, capabilities, ssoSettings] = await Promise.all(settings);

  const currentColorScheme = availableThemes.themes.find((theme) => {
    return availableThemes.selected === theme.id;
  });

  const initialState: IInitialState = {
    portalSettings,
    buildInfo,
    providers,
    capabilities,
    match: query,
    currentColorScheme,
    logoUrls,
    ssoSettings,
  };

  return initialState;
};

//TODO: get client by id for links
export const getOAuthState = async (
  clientId: string,
  isAuth: boolean
): Promise<IOAuthState> => {
  const requests = [];

  try {
    await getClient(clientId, isAuth);
  } catch (e) {
    console.log("get client");
    console.log(e);
    winston.error(e);
  }

  try {
    await getUser();
  } catch (e) {
    console.log("get user");
    console.log(e);
    winston.error(e);
  }

  try {
    await getScopeList();
  } catch (e) {
    console.log("get scopes");
    console.log(e);
    winston.error(e);
  }

  requests.push(getClient(clientId, isAuth));

  if (isAuth) {
    requests.push(getUser());
    requests.push(getScopeList());
  }

  const [client, ...rest] = await Promise.all(requests);

  const state: IOAuthState = {
    clientId,
    state: "",
    isConsent: false,
    client,
    self: undefined,
    scopes: undefined,
  };

  if (isAuth) {
    state.self = rest[0] as ISelf;
    state.scopes = rest[1] as IScope[];
  }

  return state;
};
