import { translations } from "../../../autoGeneratedTranslations";
import path from "path";
import fs from "fs";
import {
  getSettings,
  getBuildVersion,
  getAuthProviders,
  getCapabilities,
  getAppearanceTheme,
  getLogoUrls,
  getCurrentSsoSettings,
} from "@docspace/common/api/settings";
import { getUser } from "@docspace/common/api/people";
import { checkIsAuthenticated } from "@docspace/common/api/user";
import { TenantStatus } from "@docspace/common/constants";

export const getAssets = (): assetsType => {
  const manifest = fs.readFileSync(
    path.join(__dirname, "client/manifest.json"),
    "utf-8"
  );

  const assets = JSON.parse(manifest);

  return assets;
};

export const getScripts = (assets: assetsType): string[] | void => {
  if (!assets || typeof assets !== "object") return;
  const regTest = /static\/js\/.*/;
  const keys = [];

  for (let key in assets) {
    if (assets.hasOwnProperty(key) && regTest.test(key)) {
      keys.push(key);
    }
  }

  return keys;
};

export const loadPath = (language: string, nameSpace: string): string => {
  const path = translations?.get(language)?.get(nameSpace);

  return path;
};

export const getInitialState = async (
  query: MatchType
): Promise<IInitialState> => {
  let portalSettings: IPortalSettings,
    buildInfo: IBuildInfo,
    providers: ProvidersType,
    capabilities: ICapabilities,
    availableThemes: IThemes,
    isAuth: boolean,
    logoUrls: ILogoUrl[],
    ssoSettings: ISSOSettings;

  const baseSettings = [
    getSettings(),
    getBuildVersion(),
    getAppearanceTheme(),
    getLogoUrls(),
  ];

  const settings = [
    getAuthProviders(),
    getCapabilities(),
    checkIsAuthenticated(),
    getCurrentSsoSettings(),
  ];

  [portalSettings, buildInfo, availableThemes, logoUrls] = await Promise.all(
    baseSettings
  );

  if (portalSettings.tenantStatus !== TenantStatus.PortalRestore)
    [providers, capabilities, isAuth, ssoSettings] = await Promise.all(
      settings
    );

  const currentColorScheme = availableThemes.themes.find((theme) => {
    return availableThemes.selected === theme.id;
  });

  const initialState: IInitialState = {
    portalSettings,
    buildInfo,
    providers,
    capabilities,
    match: query,
    currentColorScheme,
    isAuth,
    logoUrls,
    ssoSettings,
  };

  return initialState;
};

//TODO: get client by id for links
export const getOAuthState = async (
  clientId: string,
  isAuth?: boolean
): Promise<IOAuthState> => {
  const requests = [];

  if (isAuth) requests.push(getUser());

  const [self] = await Promise.all(requests);

  const client: IOAuthClient = {
    name: "Test",
    logo: "static/images/logo/leftmenu.svg?hash=c31b569ea8c6322337cd",
    privacyURL: "https://www.google.com/?hl=RU",
    termsURL: "https://www.google.com/?hl=RU",
    scopes: ["accounts:read"],
    clientId: "1",
  };

  return { client, self };
};
