name: Frontend tests

on:
  push:
    branches: [develop, release/v*, hotfix/v*]
    paths: [packages/**, common/**]
  pull_request:
    branches: [develop, release/v*, hotfix/v*]
    paths: [packages/**, common/**]
jobs:
  playwright:
    name: "Login e2e tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: packages/login/compose.yaml
          up-flags: --build --force-recreate
          services: tests-ci
          test-container: tests-ci
          test-command: npx playwright test
  eslint:
    name: "Lint tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --no-immutable
      - name: Lint clients
        run: yarn lint
  # unit-tests:
  #   name: "Unit tests"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: enable corepack
  #       run: corepack enable
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: "yarn"
  #     - name: Clear yarn cache
  #       run: yarn cache clean
  #     - name: Install dependencies
  #       run: yarn install --no-immutable
  #     - name: Run unit tests
  #       run: yarn test
  common:
    name: "Common tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./common/tests
        run: npm install
      - name: Run common tests
        working-directory: ./common/tests
        run: npm run test
